/**
 * KidsLoveColor — Coloring Page Data
 * ====================================
 * HOW TO ADD A NEW COLORING PAGE:
 *
 * 1. Place your image file in the /svg/ folder
 * 2. Add an entry to the COLORINGS array below
 * 3. Save and refresh — it will appear automatically!
 *
 * LANGUAGES SUPPORTED: nl (Dutch), en (English), fr (French), es (Spanish), zh (Chinese)
 */

// -------------------------------------------------------
// CATEGORIES
// -------------------------------------------------------
const CATEGORIES = {
  all: {
    nl: {
      label:     'Alles',
      pageTitle: 'Gratis Kleurplaten voor Kinderen – Print & Download | KidsLoveColor.com',
      metaDesc:  'Gratis printbare kleurplaten voor kinderen: dieren, voertuigen, prinsessen, seizoenen en meer. Direct downloaden of afdrukken — 100% gratis.',
      intro:     'Kies een gratis printbare kleurplaat, klik op afdrukken en begin meteen met kleuren! Alle kleurplaten zijn geschikt voor kinderen van 3 tot 10 jaar.',
    },
    en: {
      label:     'All',
      pageTitle: 'Free Coloring Pages for Kids – Print & Download | KidsLoveColor.com',
      metaDesc:  'Free printable coloring pages for kids: animals, vehicles, princesses, seasons and more. Download or print instantly — 100% free.',
      intro:     'Choose a free printable coloring page, click print and start coloring right away! All coloring pages are suitable for children aged 3 to 10.',
    },
    fr: {
      label:     'Tout',
      pageTitle: 'Pages à Colorier Gratuites pour Enfants – Imprimer & Télécharger | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites pour enfants : animaux, véhicules, princesses, saisons et plus. Téléchargez ou imprimez instantanément — 100% gratuit.',
      intro:     'Choisissez une page à colorier gratuite, cliquez sur imprimer et commencez à colorier tout de suite ! Toutes les pages conviennent aux enfants de 3 à 10 ans.',
    },
    es: {
      label:     'Todo',
      pageTitle: 'Páginas para Colorear Gratis para Niños – Imprimir & Descargar | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear gratis para niños: animales, vehículos, princesas, estaciones y más. Descarga o imprime al instante — 100% gratis.',
      intro:     'Elige una página para colorear gratis, haz clic en imprimir ¡y empieza a colorear enseguida! Todas las páginas son aptas para niños de 3 a 10 años.',
    },
    zh: {
      label:     '全部',
      pageTitle: '免费儿童涂色页 – 打印和下载 | KidsLoveColor.com',
      metaDesc:  '免费儿童涂色页：动物、交通工具、公主、四季等。立即下载或打印 — 100%免费。',
      intro:     '选择一张免费涂色页，点击打印，立即开始涂色！所有涂色页适合3至10岁儿童。',
    },
    icon: '🎨',
  },

  dieren: {
    nl: {
      label:     'Dieren',
      pageTitle: 'Dieren Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare dieren kleurplaten voor kinderen: kat, hond, vlinder, olifant, vis, vogel en meer. Direct downloaden of afdrukken.',
      h2:        'Dieren Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten van dieren zijn altijd geliefd bij kinderen! Van schattige katten en honden tot exotische dieren uit de jungle. Allemaal gratis te printen.',
    },
    en: {
      label:     'Animals',
      pageTitle: 'Animal Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable animal coloring pages for kids: cat, dog, butterfly, elephant, fish, bird and more. Download or print instantly.',
      h2:        'Animal Coloring Pages – Free Printable',
      intro:     'Animal coloring pages are always a hit with kids! From cute cats and dogs to exotic jungle animals. All free to print.',
    },
    fr: {
      label:     'Animaux',
      pageTitle: 'Pages à Colorier Animaux pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites animaux pour enfants : chat, chien, papillon, éléphant, poisson, oiseau et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Animaux – Gratuit',
      intro:     'Les pages à colorier d\'animaux sont toujours populaires chez les enfants ! Des chats et chiens mignons aux animaux exotiques de la jungle. Tout gratuit à imprimer.',
    },
    es: {
      label:     'Animales',
      pageTitle: 'Páginas para Colorear Animales para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear animales gratis para niños: gato, perro, mariposa, elefante, pez, pájaro y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Animales – Gratis',
      intro:     '¡Las páginas para colorear de animales son siempre un éxito entre los niños! Desde gatos y perros adorables hasta animales exóticos de la jungla. Todo gratis.',
    },
    zh: {
      label:     '动物',
      pageTitle: '儿童动物涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童动物涂色页：猫、狗、蝴蝶、大象、鱼、鸟等。立即下载或打印。',
      h2:        '动物涂色页 – 免费打印',
      intro:     '动物涂色页深受儿童喜爱！从可爱的猫咪和小狗到异国丛林动物，全部免费打印。',
    },
    icon: '🐾',
    slug_en: 'animals',
  },

  voertuigen: {
    nl: {
      label:     'Voertuigen',
      pageTitle: 'Voertuigen Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare voertuigen kleurplaten voor kinderen: auto, fiets, vliegtuig, boot en meer. Direct downloaden of afdrukken.',
      h2:        'Voertuigen Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten van voertuigen zijn perfect voor jonge verkeersliefhebbers! Auto\'s, fietsen, vliegtuigen en boten — allemaal gratis te kleuren.',
    },
    en: {
      label:     'Vehicles',
      pageTitle: 'Vehicle Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable vehicle coloring pages for kids: car, bicycle, airplane, boat and more. Download or print instantly.',
      h2:        'Vehicle Coloring Pages – Free Printable',
      intro:     'Vehicle coloring pages are perfect for young traffic enthusiasts! Cars, bikes, airplanes and boats — all free to color.',
    },
    fr: {
      label:     'Véhicules',
      pageTitle: 'Pages à Colorier Véhicules pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites véhicules pour enfants : voiture, vélo, avion, bateau et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Véhicules – Gratuit',
      intro:     'Les pages à colorier de véhicules sont parfaites pour les jeunes passionnés ! Voitures, vélos, avions et bateaux — tout gratuit à colorier.',
    },
    es: {
      label:     'Vehículos',
      pageTitle: 'Páginas para Colorear Vehículos para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear vehículos gratis para niños: coche, bicicleta, avión, barco y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Vehículos – Gratis',
      intro:     '¡Las páginas para colorear de vehículos son perfectas para los jóvenes entusiastas! Coches, bicicletas, aviones y barcos — todo gratis para colorear.',
    },
    zh: {
      label:     '交通工具',
      pageTitle: '儿童交通工具涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童交通工具涂色页：汽车、自行车、飞机、船等。立即下载或打印。',
      h2:        '交通工具涂色页 – 免费打印',
      intro:     '交通工具涂色页非常适合小交通爱好者！汽车、自行车、飞机和船 — 全部免费涂色。',
    },
    icon: '🚗',
    slug_en: 'vehicles',
  },

  prinsessen: {
    nl: {
      label:     'Prinsessen & Feeën',
      pageTitle: 'Prinsessen Kleurplaten voor Meisjes – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare prinsessen kleurplaten voor meisjes: prinses, fee, sprookjesfiguren en meer. Direct downloaden of afdrukken.',
      h2:        'Prinsessen & Feeën Kleurplaten – Gratis Printbaar',
      intro:     'Prinsessen en feeën kleurplaten voor de echte dromerij! Schitterende prinsessen met kronen en feeën met toverstaven — gratis te printen.',
    },
    en: {
      label:     'Princesses & Fairies',
      pageTitle: 'Princess Coloring Pages for Girls – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable princess coloring pages for girls: princess, fairy, fairytale characters and more. Download or print instantly.',
      h2:        'Princess & Fairy Coloring Pages – Free Printable',
      intro:     'Princess and fairy coloring pages for true dreamers! Beautiful princesses with crowns and fairies with magic wands — all free to print.',
    },
    fr: {
      label:     'Princesses & Fées',
      pageTitle: 'Pages à Colorier Princesses pour Filles – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites princesses pour filles : princesse, fée, personnages de contes de fées et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Princesses & Fées – Gratuit',
      intro:     'Pages à colorier de princesses et de fées pour les vraies rêveuses ! De belles princesses avec des couronnes et des fées avec des baguettes magiques.',
    },
    es: {
      label:     'Princesas & Hadas',
      pageTitle: 'Páginas para Colorear Princesas para Niñas – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear princesas gratis para niñas: princesa, hada, personajes de cuentos y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Princesas & Hadas – Gratis',
      intro:     '¡Páginas para colorear de princesas y hadas para las verdaderas soñadoras! Hermosas princesas con coronas y hadas con varitas mágicas.',
    },
    zh: {
      label:     '公主与仙女',
      pageTitle: '儿童公主涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童公主涂色页：公主、仙女、童话人物等。立即下载或打印。',
      h2:        '公主与仙女涂色页 – 免费打印',
      intro:     '公主和仙女涂色页适合真正的梦想家！美丽的公主戴着皇冠，仙女挥舞着魔法棒，全部免费打印。',
    },
    icon: '👑',
    slug_en: 'princesses',
  },

  seizoenen: {
    nl: {
      label:     'Seizoenen & Natuur',
      pageTitle: 'Seizoenen Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare seizoenen kleurplaten voor kinderen: lente bloem, zomer zon, herfstblad, winter sneeuwpop en meer. Direct downloaden.',
      h2:        'Seizoenen & Natuur Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten over de vier seizoenen en de natuur. Van lengebloemen en zomerse zonnen tot herfstbladeren en winterse sneeuwpoppen.',
    },
    en: {
      label:     'Seasons & Nature',
      pageTitle: 'Seasonal Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable seasonal coloring pages for kids: spring flower, summer sun, autumn leaf, winter snowman and more. Download instantly.',
      h2:        'Seasons & Nature Coloring Pages – Free Printable',
      intro:     'Coloring pages about the four seasons and nature. From spring flowers and summer suns to autumn leaves and winter snowmen.',
    },
    fr: {
      label:     'Saisons & Nature',
      pageTitle: 'Pages à Colorier Saisons pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites saisons pour enfants : fleur de printemps, soleil d\'été, feuille d\'automne, bonhomme de neige et plus. Téléchargez.',
      h2:        'Pages à Colorier Saisons & Nature – Gratuit',
      intro:     'Pages à colorier sur les quatre saisons et la nature. Des fleurs du printemps aux soleils d\'été, en passant par les feuilles d\'automne et les bonshommes de neige.',
    },
    es: {
      label:     'Estaciones & Naturaleza',
      pageTitle: 'Páginas para Colorear Estaciones para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear estaciones gratis para niños: flor de primavera, sol de verano, hoja de otoño, muñeco de nieve y más. Descarga.',
      h2:        'Páginas para Colorear Estaciones & Naturaleza – Gratis',
      intro:     'Páginas para colorear sobre las cuatro estaciones y la naturaleza. Desde flores de primavera y soles de verano hasta hojas de otoño y muñecos de nieve.',
    },
    zh: {
      label:     '四季与自然',
      pageTitle: '儿童四季涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童四季涂色页：春花、夏日、秋叶、冬雪人等。立即下载或打印。',
      h2:        '四季与自然涂色页 – 免费打印',
      intro:     '关于四季和自然的涂色页。从春花、夏日到秋叶和冬雪人，应有尽有，全部免费打印。',
    },
    icon: '🌸',
    slug_en: 'seasons',
  },

  feestdagen: {
    nl: {
      label:     'Feestdagen',
      pageTitle: 'Feestdagen Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare feestdagen kleurplaten voor kinderen: kerst, sinterklaas, pasen, halloween en meer. Direct downloaden of afdrukken.',
      h2:        'Feestdagen Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten voor elk feest! Van kerst en sinterklaas tot pasen en halloween. Perfect als activiteit tijdens de feestdagen.',
    },
    en: {
      label:     'Holidays',
      pageTitle: 'Holiday Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable holiday coloring pages for kids: Christmas, Easter, Halloween and more. Download or print instantly.',
      h2:        'Holiday Coloring Pages – Free Printable',
      intro:     'Coloring pages for every celebration! From Christmas and Easter to Halloween. Perfect as an activity during the holidays.',
    },
    fr: {
      label:     'Fêtes',
      pageTitle: 'Pages à Colorier Fêtes pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites fêtes pour enfants : Noël, Pâques, Halloween et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Fêtes – Gratuit',
      intro:     'Pages à colorier pour chaque célébration ! De Noël et Pâques à Halloween. Parfait comme activité pendant les fêtes.',
    },
    es: {
      label:     'Fiestas',
      pageTitle: 'Páginas para Colorear Fiestas para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear fiestas gratis para niños: Navidad, Pascua, Halloween y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Fiestas – Gratis',
      intro:     '¡Páginas para colorear para cada celebración! Desde Navidad y Pascua hasta Halloween. Perfectas como actividad durante las fiestas.',
    },
    zh: {
      label:     '节日',
      pageTitle: '儿童节日涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童节日涂色页：圣诞节、复活节、万圣节等。立即下载或打印。',
      h2:        '节日涂色页 – 免费打印',
      intro:     '每个节日都有涂色页！从圣诞节和复活节到万圣节。节日期间的完美涂色活动，全部免费。',
    },
    icon: '🎉',
    slug_en: 'holidays',
  },

  eten: {
    nl: {
      label:     'Eten & Drinken',
      pageTitle: 'Eten Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare eten kleurplaten voor kinderen: fruit, groente, snoep, taarten en meer. Direct downloaden of afdrukken.',
      h2:        'Eten & Drinken Kleurplaten – Gratis Printbaar',
      intro:     'Leuke kleurplaten van eten en drinken voor kinderen. Van appels en bananen tot taarten en snoepjes.',
    },
    en: {
      label:     'Food & Drinks',
      pageTitle: 'Food Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable food coloring pages for kids: fruit, vegetables, candy, cakes and more. Download or print instantly.',
      h2:        'Food & Drink Coloring Pages – Free Printable',
      intro:     'Fun food and drink coloring pages for kids. From apples and bananas to cakes and candies.',
    },
    fr: {
      label:     'Nourriture & Boissons',
      pageTitle: 'Pages à Colorier Nourriture pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites nourriture pour enfants : fruits, légumes, bonbons, gâteaux et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Nourriture & Boissons – Gratuit',
      intro:     'Pages à colorier amusantes de nourriture et boissons pour enfants. Des pommes et bananes aux gâteaux et bonbons.',
    },
    es: {
      label:     'Comida & Bebidas',
      pageTitle: 'Páginas para Colorear Comida para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear comida gratis para niños: frutas, verduras, dulces, pasteles y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Comida & Bebidas – Gratis',
      intro:     'Divertidas páginas para colorear de comida y bebidas para niños. De manzanas y plátanos a pasteles y dulces.',
    },
    zh: {
      label:     '食物与饮料',
      pageTitle: '儿童食物涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童食物涂色页：水果、蔬菜、糖果、蛋糕等。立即下载或打印。',
      h2:        '食物与饮料涂色页 – 免费打印',
      intro:     '有趣的儿童食物和饮料涂色页。从苹果和香蕉到蛋糕和糖果，全部免费。',
    },
    icon: '🍎',
    slug_en: 'food',
  },

  ruimte: {
    nl: {
      label:     'Ruimte',
      pageTitle: 'Ruimte Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare ruimte kleurplaten voor kinderen: raket, planeten, sterren, astronaut en meer. Direct downloaden of afdrukken.',
      h2:        'Ruimte Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten over de ruimte voor kleine ruimtevaarders! Raketten, planeten, sterren en astronauten — gratis te kleuren.',
    },
    en: {
      label:     'Space',
      pageTitle: 'Space Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable space coloring pages for kids: rocket, planets, stars, astronaut and more. Download or print instantly.',
      h2:        'Space Coloring Pages – Free Printable',
      intro:     'Space coloring pages for little astronauts! Rockets, planets, stars and astronauts — all free to color.',
    },
    fr: {
      label:     'Espace',
      pageTitle: 'Pages à Colorier Espace pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites espace pour enfants : fusée, planètes, étoiles, astronaute et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Espace – Gratuit',
      intro:     'Pages à colorier sur l\'espace pour les petits astronautes ! Fusées, planètes, étoiles et astronautes — tout gratuit à colorier.',
    },
    es: {
      label:     'Espacio',
      pageTitle: 'Páginas para Colorear Espacio para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear espacio gratis para niños: cohete, planetas, estrellas, astronauta y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Espacio – Gratis',
      intro:     '¡Páginas para colorear sobre el espacio para pequeños astronautas! Cohetes, planetas, estrellas y astronautas — todo gratis para colorear.',
    },
    zh: {
      label:     '太空',
      pageTitle: '儿童太空涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童太空涂色页：火箭、行星、星星、宇航员等。立即下载或打印。',
      h2:        '太空涂色页 – 免费打印',
      intro:     '太空涂色页适合小小宇航员！火箭、行星、星星和宇航员 — 全部免费涂色。',
    },
    icon: '🚀',
    slug_en: 'space',
  },
};

// -------------------------------------------------------
// COLORING PAGES
// -------------------------------------------------------
const COLORINGS = [

  // ===== DIEREN / ANIMALS / ANIMAUX / ANIMALES / 动物 =====
  {
    id: 1,
    slug: 'kat',
    category: 'dieren',
    difficulty: 'easy',
    img: '../svg/kat.svg',
    nl: {
      title:       'Lieve Kat',
      description: 'Gratis printbare kleurplaat van een lieve kat met snorharen en een strik. Makkelijk te kleuren voor kinderen.',
      keywords:    'kat kleurplaat gratis poes kitten dier huisdier kinderkamer',
      altText:     'Gratis kleurplaat lieve kat – afdrukken voor kinderen',
    },
    en: {
      title:       'Cute Cat',
      description: 'Free printable coloring page of a cute cat with whiskers and a bow. Easy to color for children.',
      keywords:    'cat coloring page free kitten pet animal kids printable',
      altText:     'Free coloring page cute cat – printable for kids',
    },
    fr: {
      title:       'Joli Chat',
      description: 'Page à colorier gratuite d\'un joli chat avec des moustaches et un nœud. Facile à colorier pour les enfants.',
      keywords:    'chat coloriage gratuit chaton animal compagnie enfants imprimable',
      altText:     'Page à colorier gratuite joli chat – à imprimer pour enfants',
    },
    es: {
      title:       'Lindo Gato',
      description: 'Página para colorear gratis de un lindo gato con bigotes y un lazo. Fácil de colorear para niños.',
      keywords:    'gato colorear gratis gatito mascota animal niños imprimible',
      altText:     'Página para colorear gratis lindo gato – para imprimir para niños',
    },
    zh: {
      title:       '可爱小猫',
      description: '免费儿童涂色页，画的是一只有胡须和蝴蝶结的可爱小猫。简单易涂色。',
      keywords:    '猫 涂色 免费 小猫 宠物 动物 儿童 可打印',
      altText:     '免费涂色页 可爱小猫 – 儿童打印',
    },
  },
  {
    id: 2,
    slug: 'hond',
    category: 'dieren',
    difficulty: 'easy',
    img: '../svg/hond.svg',
    nl: {
      title:       'Vrolijke Hond',
      description: 'Gratis printbare kleurplaat van een vrolijke hond met hangoren. Makkelijk te kleuren, perfect voor jonge kinderen.',
      keywords:    'hond kleurplaat gratis puppy hond dier huisdier vrolijk',
      altText:     'Gratis kleurplaat vrolijke hond – afdrukken voor kinderen',
    },
    en: {
      title:       'Happy Dog',
      description: 'Free printable coloring page of a happy dog with floppy ears. Easy to color, perfect for young children.',
      keywords:    'dog coloring page free puppy pet animal kids happy printable',
      altText:     'Free coloring page happy dog – printable for kids',
    },
    fr: {
      title:       'Joyeux Chien',
      description: 'Page à colorier gratuite d\'un joyeux chien avec de grandes oreilles tombantes. Facile à colorier pour les jeunes enfants.',
      keywords:    'chien coloriage gratuit chiot animal compagnie enfants joyeux imprimable',
      altText:     'Page à colorier gratuite joyeux chien – à imprimer pour enfants',
    },
    es: {
      title:       'Perro Feliz',
      description: 'Página para colorear gratis de un perro feliz con orejas caídas. Fácil de colorear, perfecta para niños pequeños.',
      keywords:    'perro colorear gratis cachorro mascota animal niños feliz imprimible',
      altText:     'Página para colorear gratis perro feliz – para imprimir para niños',
    },
    zh: {
      title:       '快乐小狗',
      description: '免费儿童涂色页，画的是一只有垂耳的快乐小狗。简单易涂，适合幼童。',
      keywords:    '狗 涂色 免费 小狗 宠物 动物 儿童 快乐 可打印',
      altText:     '免费涂色页 快乐小狗 – 儿童打印',
    },
  },
  {
    id: 3,
    slug: 'vlinder',
    category: 'dieren',
    difficulty: 'easy',
    img: '../svg/vlinder.svg',
    nl: {
      title:       'Mooie Vlinder',
      description: 'Gratis printbare kleurplaat van een mooie vlinder met symmetrische vleugels. Ideaal om creatief te kleuren.',
      keywords:    'vlinder kleurplaat gratis insect natuur vleugels lente',
      altText:     'Gratis kleurplaat mooie vlinder – afdrukken voor kinderen',
    },
    en: {
      title:       'Beautiful Butterfly',
      description: 'Free printable coloring page of a beautiful butterfly with symmetrical wings. Ideal for creative coloring.',
      keywords:    'butterfly coloring page free insect nature wings spring kids',
      altText:     'Free coloring page beautiful butterfly – printable for kids',
    },
    fr: {
      title:       'Beau Papillon',
      description: 'Page à colorier gratuite d\'un beau papillon aux ailes symétriques. Idéale pour une coloration créative.',
      keywords:    'papillon coloriage gratuit insecte nature ailes printemps enfants',
      altText:     'Page à colorier gratuite beau papillon – à imprimer pour enfants',
    },
    es: {
      title:       'Bella Mariposa',
      description: 'Página para colorear gratis de una bella mariposa con alas simétricas. Ideal para colorear de forma creativa.',
      keywords:    'mariposa colorear gratis insecto naturaleza alas primavera niños',
      altText:     'Página para colorear gratis bella mariposa – para imprimir para niños',
    },
    zh: {
      title:       '美丽蝴蝶',
      description: '免费儿童涂色页，画的是一只有对称翅膀的美丽蝴蝶。非常适合创意涂色。',
      keywords:    '蝴蝶 涂色 免费 昆虫 自然 翅膀 春天 儿童',
      altText:     '免费涂色页 美丽蝴蝶 – 儿童打印',
    },
  },
  {
    id: 4,
    slug: 'olifant',
    category: 'dieren',
    difficulty: 'medium',
    img: '../svg/olifant.svg',
    nl: {
      title:       'Grote Olifant',
      description: 'Gratis printbare kleurplaat van een grote olifant met grote oren en een lange slurf. Leuk voor dierenliefhebbers.',
      keywords:    'olifant kleurplaat gratis dier savanne Afrika jungle slurf',
      altText:     'Gratis kleurplaat grote olifant – afdrukken voor kinderen',
    },
    en: {
      title:       'Big Elephant',
      description: 'Free printable coloring page of a big elephant with large ears and a long trunk. Fun for animal lovers.',
      keywords:    'elephant coloring page free animal safari Africa trunk kids',
      altText:     'Free coloring page big elephant – printable for kids',
    },
    fr: {
      title:       'Grand Éléphant',
      description: 'Page à colorier gratuite d\'un grand éléphant aux grandes oreilles et à la longue trompe. Amusant pour les amoureux des animaux.',
      keywords:    'éléphant coloriage gratuit animal safari Afrique trompe enfants',
      altText:     'Page à colorier gratuite grand éléphant – à imprimer pour enfants',
    },
    es: {
      title:       'Gran Elefante',
      description: 'Página para colorear gratis de un gran elefante con grandes orejas y una larga trompa. Divertida para amantes de los animales.',
      keywords:    'elefante colorear gratis animal safari África trompa niños',
      altText:     'Página para colorear gratis gran elefante – para imprimir para niños',
    },
    zh: {
      title:       '大象',
      description: '免费儿童涂色页，画的是一头有大耳朵和长鼻子的大象。动物爱好者的最爱。',
      keywords:    '大象 涂色 免费 动物 非洲 鼻子 儿童 可打印',
      altText:     '免费涂色页 大象 – 儿童打印',
    },
  },
  {
    id: 5,
    slug: 'vis',
    category: 'dieren',
    difficulty: 'easy',
    img: '../svg/vis.svg',
    nl: {
      title:       'Zwemmende Vis',
      description: 'Gratis printbare kleurplaat van een zwemmende vis met schubben en vinnen. Kleurrijke onderwaterwereld voor kinderen.',
      keywords:    'vis kleurplaat gratis zee water oceaan zwemmen schubben',
      altText:     'Gratis kleurplaat zwemmende vis – afdrukken voor kinderen',
    },
    en: {
      title:       'Swimming Fish',
      description: 'Free printable coloring page of a swimming fish with scales and fins. Colorful underwater world for kids.',
      keywords:    'fish coloring page free sea water ocean swimming scales kids',
      altText:     'Free coloring page swimming fish – printable for kids',
    },
    fr: {
      title:       'Poisson Nageur',
      description: 'Page à colorier gratuite d\'un poisson nageur avec des écailles et des nageoires. Monde sous-marin coloré pour enfants.',
      keywords:    'poisson coloriage gratuit mer eau océan nager écailles enfants',
      altText:     'Page à colorier gratuite poisson nageur – à imprimer pour enfants',
    },
    es: {
      title:       'Pez Nadador',
      description: 'Página para colorear gratis de un pez nadador con escamas y aletas. Colorido mundo submarino para niños.',
      keywords:    'pez colorear gratis mar agua océano nadar escamas niños',
      altText:     'Página para colorear gratis pez nadador – para imprimir para niños',
    },
    zh: {
      title:       '游泳的鱼',
      description: '免费儿童涂色页，画的是一条有鳞片和鱼鳍的游泳鱼。色彩斑斓的海底世界。',
      keywords:    '鱼 涂色 免费 海洋 水 游泳 鳞片 儿童',
      altText:     '免费涂色页 游泳的鱼 – 儿童打印',
    },
  },
  {
    id: 6,
    slug: 'vogel',
    category: 'dieren',
    difficulty: 'easy',
    img: '../svg/vogel.svg',
    nl: {
      title:       'Zingende Vogel',
      description: 'Gratis printbare kleurplaat van een zingende vogel op een tak. Schattig ontwerp voor jonge dierenliefhebbers.',
      keywords:    'vogel kleurplaat gratis vleugels natuur tak boom zingen',
      altText:     'Gratis kleurplaat zingende vogel op tak – afdrukken voor kinderen',
    },
    en: {
      title:       'Singing Bird',
      description: 'Free printable coloring page of a singing bird on a branch. Cute design for young animal lovers.',
      keywords:    'bird coloring page free wings nature branch tree singing kids',
      altText:     'Free coloring page singing bird on branch – printable for kids',
    },
    fr: {
      title:       'Oiseau Chanteur',
      description: 'Page à colorier gratuite d\'un oiseau chanteur sur une branche. Mignon design pour les jeunes amoureux des animaux.',
      keywords:    'oiseau coloriage gratuit ailes nature branche arbre chanter enfants',
      altText:     'Page à colorier gratuite oiseau chanteur sur branche – à imprimer pour enfants',
    },
    es: {
      title:       'Pájaro Cantor',
      description: 'Página para colorear gratis de un pájaro cantor en una rama. Diseño lindo para jóvenes amantes de los animales.',
      keywords:    'pájaro colorear gratis alas naturaleza rama árbol cantar niños',
      altText:     'Página para colorear gratis pájaro cantor en rama – para imprimir para niños',
    },
    zh: {
      title:       '歌唱小鸟',
      description: '免费儿童涂色页，画的是一只站在树枝上唱歌的小鸟。可爱设计，适合小动物爱好者。',
      keywords:    '鸟 涂色 免费 翅膀 自然 树枝 唱歌 儿童',
      altText:     '免费涂色页 歌唱小鸟在树枝上 – 儿童打印',
    },
  },

  // ===== VOERTUIGEN / VEHICLES / VÉHICULES / VEHÍCULOS / 交通工具 =====
  {
    id: 7,
    slug: 'auto',
    category: 'voertuigen',
    difficulty: 'easy',
    img: '../svg/auto.svg',
    nl: {
      title:       'Coole Auto',
      description: 'Gratis printbare kleurplaat van een coole auto. Leuke activiteit voor jonge autoliefhebbers, makkelijk te kleuren.',
      keywords:    'auto kleurplaat gratis voertuig rijden weg wielen ramen',
      altText:     'Gratis kleurplaat coole auto – afdrukken voor kinderen',
    },
    en: {
      title:       'Cool Car',
      description: 'Free printable coloring page of a cool car. Fun activity for young car enthusiasts, easy to color.',
      keywords:    'car coloring page free vehicle driving road wheels windows kids',
      altText:     'Free coloring page cool car – printable for kids',
    },
    fr: {
      title:       'Belle Voiture',
      description: 'Page à colorier gratuite d\'une belle voiture. Activité amusante pour les jeunes passionnés, facile à colorier.',
      keywords:    'voiture coloriage gratuit véhicule conduite route roues enfants',
      altText:     'Page à colorier gratuite belle voiture – à imprimer pour enfants',
    },
    es: {
      title:       'Coche Genial',
      description: 'Página para colorear gratis de un coche genial. Actividad divertida para jóvenes entusiastas, fácil de colorear.',
      keywords:    'coche colorear gratis vehículo conducir carretera ruedas niños',
      altText:     'Página para colorear gratis coche genial – para imprimir para niños',
    },
    zh: {
      title:       '酷炫汽车',
      description: '免费儿童涂色页，画的是一辆酷炫汽车。适合小汽车爱好者的有趣活动，简单易涂。',
      keywords:    '汽车 涂色 免费 交通工具 驾驶 道路 车轮 儿童',
      altText:     '免费涂色页 酷炫汽车 – 儿童打印',
    },
  },
  {
    id: 8,
    slug: 'fiets',
    category: 'voertuigen',
    difficulty: 'medium',
    img: '../svg/fiets.svg',
    nl: {
      title:       'Fiets',
      description: 'Gratis printbare kleurplaat van een fiets met details. Leerzame kleurplaat over de fiets voor kinderen.',
      keywords:    'fiets kleurplaat gratis rijwiel fietsen wielersport trappers wielen',
      altText:     'Gratis kleurplaat fiets – afdrukken voor kinderen',
    },
    en: {
      title:       'Bicycle',
      description: 'Free printable coloring page of a detailed bicycle. Educational coloring page about bikes for children.',
      keywords:    'bicycle coloring page free bike cycling wheels pedals kids',
      altText:     'Free coloring page bicycle – printable for kids',
    },
    fr: {
      title:       'Vélo',
      description: 'Page à colorier gratuite d\'un vélo détaillé. Page éducative sur les vélos pour les enfants.',
      keywords:    'vélo coloriage gratuit cyclisme roues pédales enfants imprimable',
      altText:     'Page à colorier gratuite vélo – à imprimer pour enfants',
    },
    es: {
      title:       'Bicicleta',
      description: 'Página para colorear gratis de una bicicleta detallada. Página educativa sobre bicicletas para niños.',
      keywords:    'bicicleta colorear gratis ciclismo ruedas pedales niños imprimible',
      altText:     'Página para colorear gratis bicicleta – para imprimir para niños',
    },
    zh: {
      title:       '自行车',
      description: '免费儿童涂色页，画的是一辆详细的自行车。关于自行车的教育性涂色页。',
      keywords:    '自行车 涂色 免费 骑车 车轮 踏板 儿童 可打印',
      altText:     '免费涂色页 自行车 – 儿童打印',
    },
  },
  {
    id: 9,
    slug: 'vliegtuig',
    category: 'voertuigen',
    difficulty: 'medium',
    img: '../svg/vliegtuig.svg',
    nl: {
      title:       'Vliegtuig',
      description: 'Gratis printbare kleurplaat van een vliegtuig met vleugels en raampjes. Ideaal voor kinderen die van vliegen dromen.',
      keywords:    'vliegtuig kleurplaat gratis vliegen lucht wolken ramen vleugels',
      altText:     'Gratis kleurplaat vliegtuig – afdrukken voor kinderen',
    },
    en: {
      title:       'Airplane',
      description: 'Free printable coloring page of an airplane with wings and windows. Ideal for children who dream of flying.',
      keywords:    'airplane coloring page free plane flying sky clouds wings kids',
      altText:     'Free coloring page airplane – printable for kids',
    },
    fr: {
      title:       'Avion',
      description: 'Page à colorier gratuite d\'un avion avec des ailes et des hublots. Idéale pour les enfants qui rêvent de voler.',
      keywords:    'avion coloriage gratuit vol ciel nuages ailes enfants imprimable',
      altText:     'Page à colorier gratuite avion – à imprimer pour enfants',
    },
    es: {
      title:       'Avión',
      description: 'Página para colorear gratis de un avión con alas y ventanas. Ideal para niños que sueñan con volar.',
      keywords:    'avión colorear gratis volar cielo nubes alas niños imprimible',
      altText:     'Página para colorear gratis avión – para imprimir para niños',
    },
    zh: {
      title:       '飞机',
      description: '免费儿童涂色页，画的是一架有翅膀和窗户的飞机。适合梦想飞翔的孩子。',
      keywords:    '飞机 涂色 免费 飞行 天空 云 翅膀 儿童 可打印',
      altText:     '免费涂色页 飞机 – 儿童打印',
    },
  },
  {
    id: 10,
    slug: 'boot',
    category: 'voertuigen',
    difficulty: 'medium',
    img: '../svg/boot.svg',
    nl: {
      title:       'Zeilboot',
      description: 'Gratis printbare kleurplaat van een zeilboot op zee met mast en zeilen. Perfect voor zomerse kleursessies.',
      keywords:    'boot zeilboot kleurplaat gratis zee water varen mast zeilen golven',
      altText:     'Gratis kleurplaat zeilboot op zee – afdrukken voor kinderen',
    },
    en: {
      title:       'Sailboat',
      description: 'Free printable coloring page of a sailboat at sea with mast and sails. Perfect for summer coloring sessions.',
      keywords:    'sailboat coloring page free boat sea water sailing mast waves kids',
      altText:     'Free coloring page sailboat at sea – printable for kids',
    },
    fr: {
      title:       'Voilier',
      description: 'Page à colorier gratuite d\'un voilier en mer avec mât et voiles. Parfaite pour les séances de coloriage estivales.',
      keywords:    'voilier coloriage gratuit bateau mer eau navigation mât vagues enfants',
      altText:     'Page à colorier gratuite voilier en mer – à imprimer pour enfants',
    },
    es: {
      title:       'Velero',
      description: 'Página para colorear gratis de un velero en el mar con mástil y velas. Perfecta para sesiones de coloreo veraniegas.',
      keywords:    'velero colorear gratis barco mar agua navegar mástil olas niños',
      altText:     'Página para colorear gratis velero en el mar – para imprimir para niños',
    },
    zh: {
      title:       '帆船',
      description: '免费儿童涂色页，画的是一艘有桅杆和帆的海上帆船。完美的夏日涂色活动。',
      keywords:    '帆船 涂色 免费 船 海洋 水 航行 桅杆 波浪 儿童',
      altText:     '免费涂色页 海上帆船 – 儿童打印',
    },
  },

  // ===== PRINSESSEN & FEEËN / PRINCESSES / PRINCESSES & FÉES / PRINCESAS / 公主与仙女 =====
  {
    id: 11,
    slug: 'prinses',
    category: 'prinsessen',
    difficulty: 'medium',
    img: '../svg/prinses.svg',
    nl: {
      title:       'Mooie Prinses',
      description: 'Gratis printbare kleurplaat van een mooie prinses met kroon en jurk. Geliefd bij meisjes die van sprookjes houden.',
      keywords:    'prinses kleurplaat gratis kroon jurk kasteel sprookje meisjes fee',
      altText:     'Gratis kleurplaat mooie prinses met kroon – afdrukken voor kinderen',
    },
    en: {
      title:       'Beautiful Princess',
      description: 'Free printable coloring page of a beautiful princess with crown and dress. Popular with girls who love fairytales.',
      keywords:    'princess coloring page free crown dress castle fairytale girls fairy',
      altText:     'Free coloring page beautiful princess with crown – printable for kids',
    },
    fr: {
      title:       'Belle Princesse',
      description: 'Page à colorier gratuite d\'une belle princesse avec couronne et robe. Populaire auprès des filles qui aiment les contes de fées.',
      keywords:    'princesse coloriage gratuit couronne robe château conte de fées filles fée',
      altText:     'Page à colorier gratuite belle princesse avec couronne – à imprimer pour enfants',
    },
    es: {
      title:       'Hermosa Princesa',
      description: 'Página para colorear gratis de una hermosa princesa con corona y vestido. Popular entre las niñas que aman los cuentos de hadas.',
      keywords:    'princesa colorear gratis corona vestido castillo cuento de hadas niñas hada',
      altText:     'Página para colorear gratis hermosa princesa con corona – para imprimir para niños',
    },
    zh: {
      title:       '美丽公主',
      description: '免费儿童涂色页，画的是一位戴着皇冠、穿着裙子的美丽公主。深受爱好童话的女孩喜爱。',
      keywords:    '公主 涂色 免费 皇冠 裙子 城堡 童话 女孩 仙女',
      altText:     '免费涂色页 美丽公主戴皇冠 – 儿童打印',
    },
  },
  {
    id: 12,
    slug: 'fee',
    category: 'prinsessen',
    difficulty: 'medium',
    img: '../svg/fee.svg',
    nl: {
      title:       'Kleine Fee',
      description: 'Gratis printbare kleurplaat van een kleine fee met vleugels en toverstaf. Magisch ontwerp voor kleine dromerij.',
      keywords:    'fee kleurplaat gratis magie vleugels toverstaf elfje meisjes prinsessen',
      altText:     'Gratis kleurplaat kleine fee met vleugels – afdrukken voor kinderen',
    },
    en: {
      title:       'Little Fairy',
      description: 'Free printable coloring page of a little fairy with wings and a magic wand. Magical design for little dreamers.',
      keywords:    'fairy coloring page free magic wings wand pixie girls princess kids',
      altText:     'Free coloring page little fairy with wings – printable for kids',
    },
    fr: {
      title:       'Petite Fée',
      description: 'Page à colorier gratuite d\'une petite fée avec des ailes et une baguette magique. Design magique pour les petites rêveuses.',
      keywords:    'fée coloriage gratuit magie ailes baguette magique lutin filles princesses',
      altText:     'Page à colorier gratuite petite fée avec ailes – à imprimer pour enfants',
    },
    es: {
      title:       'Pequeña Hada',
      description: 'Página para colorear gratis de una pequeña hada con alas y una varita mágica. Diseño mágico para pequeñas soñadoras.',
      keywords:    'hada colorear gratis magia alas varita mágica duendes niñas princesas',
      altText:     'Página para colorear gratis pequeña hada con alas – para imprimir para niños',
    },
    zh: {
      title:       '小仙女',
      description: '免费儿童涂色页，画的是一位有翅膀和魔法棒的小仙女。魔法设计，适合小梦想家。',
      keywords:    '仙女 涂色 免费 魔法 翅膀 魔法棒 小精灵 女孩 公主',
      altText:     '免费涂色页 小仙女有翅膀 – 儿童打印',
    },
  },

  // ===== SEIZOENEN & NATUUR / SEASONS / SAISONS / ESTACIONES / 四季 =====
  {
    id: 13,
    slug: 'bloem',
    category: 'seizoenen',
    difficulty: 'easy',
    img: '../svg/bloem.svg',
    nl: {
      title:       'Grote Bloem',
      description: 'Gratis printbare kleurplaat van een grote bloem met bij. Lente-thema kleurplaat, makkelijk voor jonge kinderen.',
      keywords:    'bloem kleurplaat gratis lente natuur tuin bij bloemblaadjes voorjaar',
      altText:     'Gratis kleurplaat grote bloem met bij – afdrukken voor kinderen',
    },
    en: {
      title:       'Big Flower',
      description: 'Free printable coloring page of a big flower with a bee. Spring theme coloring page, easy for young children.',
      keywords:    'flower coloring page free spring nature garden bee petals kids',
      altText:     'Free coloring page big flower with bee – printable for kids',
    },
    fr: {
      title:       'Grande Fleur',
      description: 'Page à colorier gratuite d\'une grande fleur avec une abeille. Page à thème printanier, facile pour les jeunes enfants.',
      keywords:    'fleur coloriage gratuit printemps nature jardin abeille pétales enfants',
      altText:     'Page à colorier gratuite grande fleur avec abeille – à imprimer pour enfants',
    },
    es: {
      title:       'Gran Flor',
      description: 'Página para colorear gratis de una gran flor con una abeja. Página con tema primaveral, fácil para niños pequeños.',
      keywords:    'flor colorear gratis primavera naturaleza jardín abeja pétalos niños',
      altText:     'Página para colorear gratis gran flor con abeja – para imprimir para niños',
    },
    zh: {
      title:       '大花朵',
      description: '免费儿童涂色页，画的是一朵有蜜蜂的大花朵。春天主题涂色页，适合幼童。',
      keywords:    '花 涂色 免费 春天 自然 花园 蜜蜂 花瓣 儿童',
      altText:     '免费涂色页 大花朵有蜜蜂 – 儿童打印',
    },
  },
  {
    id: 14,
    slug: 'sneeuwpop',
    category: 'seizoenen',
    difficulty: 'easy',
    img: '../svg/sneeuwpop.svg',
    nl: {
      title:       'Vrolijke Sneeuwpop',
      description: 'Gratis printbare kleurplaat van een vrolijke sneeuwpop met hoed en sjaal. Perfecte winterse kleurplaat voor kinderen.',
      keywords:    'sneeuwpop kleurplaat gratis winter sneeuw ijs kerst hoed sjaal',
      altText:     'Gratis kleurplaat vrolijke sneeuwpop – afdrukken voor kinderen',
    },
    en: {
      title:       'Happy Snowman',
      description: 'Free printable coloring page of a happy snowman with hat and scarf. Perfect winter coloring page for children.',
      keywords:    'snowman coloring page free winter snow ice christmas hat scarf kids',
      altText:     'Free coloring page happy snowman – printable for kids',
    },
    fr: {
      title:       'Joyeux Bonhomme de Neige',
      description: 'Page à colorier gratuite d\'un joyeux bonhomme de neige avec chapeau et écharpe. Parfaite page hivernale pour enfants.',
      keywords:    'bonhomme de neige coloriage gratuit hiver neige glace noël chapeau écharpe enfants',
      altText:     'Page à colorier gratuite joyeux bonhomme de neige – à imprimer pour enfants',
    },
    es: {
      title:       'Muñeco de Nieve Feliz',
      description: 'Página para colorear gratis de un muñeco de nieve feliz con sombrero y bufanda. Perfecta página invernal para niños.',
      keywords:    'muñeco de nieve colorear gratis invierno nieve hielo navidad sombrero bufanda niños',
      altText:     'Página para colorear gratis muñeco de nieve feliz – para imprimir para niños',
    },
    zh: {
      title:       '快乐雪人',
      description: '免费儿童涂色页，画的是一个戴帽子和围巾的快乐雪人。完美的冬季涂色页。',
      keywords:    '雪人 涂色 免费 冬天 雪 冰 圣诞节 帽子 围巾 儿童',
      altText:     '免费涂色页 快乐雪人 – 儿童打印',
    },
  },
  {
    id: 15,
    slug: 'zon',
    category: 'seizoenen',
    difficulty: 'easy',
    img: '../svg/zon.svg',
    nl: {
      title:       'Stralende Zon',
      description: 'Gratis printbare kleurplaat van een stralende zon met gezicht en zonnestralen. Vrolijk zomer-ontwerp voor kinderen.',
      keywords:    'zon kleurplaat gratis zomer warm zonnig stralen gezicht lachen',
      altText:     'Gratis kleurplaat stralende zon met gezicht – afdrukken voor kinderen',
    },
    en: {
      title:       'Shining Sun',
      description: 'Free printable coloring page of a shining sun with a face and rays. Cheerful summer design for children.',
      keywords:    'sun coloring page free summer warm sunny rays face smile kids',
      altText:     'Free coloring page shining sun with face – printable for kids',
    },
    fr: {
      title:       'Soleil Brillant',
      description: 'Page à colorier gratuite d\'un soleil brillant avec un visage et des rayons. Design estival joyeux pour les enfants.',
      keywords:    'soleil coloriage gratuit été chaud ensoleillé rayons visage sourire enfants',
      altText:     'Page à colorier gratuite soleil brillant avec visage – à imprimer pour enfants',
    },
    es: {
      title:       'Sol Brillante',
      description: 'Página para colorear gratis de un sol brillante con cara y rayos. Alegre diseño veraniego para niños.',
      keywords:    'sol colorear gratis verano cálido soleado rayos cara sonrisa niños',
      altText:     'Página para colorear gratis sol brillante con cara – para imprimir para niños',
    },
    zh: {
      title:       '闪亮太阳',
      description: '免费儿童涂色页，画的是一个有笑脸和光芒的闪亮太阳。欢快的夏日设计。',
      keywords:    '太阳 涂色 免费 夏天 温暖 阳光 光芒 笑脸 儿童',
      altText:     '免费涂色页 闪亮太阳有笑脸 – 儿童打印',
    },
  },
  {
    id: 16,
    slug: 'blad',
    category: 'seizoenen',
    difficulty: 'medium',
    img: '../svg/blad.svg',
    nl: {
      title:       'Herfstblad',
      description: 'Gratis printbare kleurplaat van een herfstblad met nerven, eikel en paddenstoel. Prachtig herfst-thema ontwerp.',
      keywords:    'herfstblad kleurplaat gratis herfst boom natuur eikel paddenstoel bladeren',
      altText:     'Gratis kleurplaat herfstblad met eikel – afdrukken voor kinderen',
    },
    en: {
      title:       'Autumn Leaf',
      description: 'Free printable coloring page of an autumn leaf with veins, acorn and mushroom. Beautiful fall theme design.',
      keywords:    'autumn leaf coloring page free fall tree nature acorn mushroom kids',
      altText:     'Free coloring page autumn leaf with acorn – printable for kids',
    },
    fr: {
      title:       'Feuille d\'Automne',
      description: 'Page à colorier gratuite d\'une feuille d\'automne avec nervures, gland et champignon. Magnifique design aux couleurs d\'automne.',
      keywords:    'feuille automne coloriage gratuit arbre nature gland champignon enfants',
      altText:     'Page à colorier gratuite feuille d\'automne avec gland – à imprimer pour enfants',
    },
    es: {
      title:       'Hoja de Otoño',
      description: 'Página para colorear gratis de una hoja de otoño con nervios, bellota y seta. Hermoso diseño con tema otoñal.',
      keywords:    'hoja otoño colorear gratis árbol naturaleza bellota seta niños',
      altText:     'Página para colorear gratis hoja de otoño con bellota – para imprimir para niños',
    },
    zh: {
      title:       '秋叶',
      description: '免费儿童涂色页，画的是一片有叶脉、橡实和蘑菇的秋叶。美丽的秋天主题设计。',
      keywords:    '秋叶 涂色 免费 秋天 树 自然 橡实 蘑菇 儿童',
      altText:     '免费涂色页 秋叶有橡实 – 儿童打印',
    },
  },

];
