/**
 * KidsLoveColor — Coloring Page Data
 * ====================================
 * HOW TO ADD A NEW COLORING PAGE:
 *
 * 1. Place your image file in the /svg/ folder
 * 2. Add an entry to the COLORINGS array below
 * 3. Save and refresh — it will appear automatically!
 *
 * LANGUAGES SUPPORTED: nl (Dutch), en (English), fr (French), es (Spanish), zh (Chinese)
 */

// -------------------------------------------------------
// CATEGORIES
// -------------------------------------------------------
const CATEGORIES = {
  all: {
    nl: {
      label:     'Alles',
      pageTitle: 'Gratis Kleurplaten voor Kinderen – Print & Download | KidsLoveColor.com',
      metaDesc:  'Gratis printbare kleurplaten voor kinderen: dieren, voertuigen, prinsessen, seizoenen en meer. Direct downloaden of afdrukken — 100% gratis.',
      intro:     'Kies een gratis printbare kleurplaat, klik op afdrukken en begin meteen met kleuren! Alle kleurplaten zijn geschikt voor kinderen van 3 tot 10 jaar.',
    },
    en: {
      label:     'All',
      pageTitle: 'Free Coloring Pages for Kids – Print & Download | KidsLoveColor.com',
      metaDesc:  'Free printable coloring pages for kids: animals, vehicles, princesses, seasons and more. Download or print instantly — 100% free.',
      intro:     'Choose a free printable coloring page, click print and start coloring right away! All coloring pages are suitable for children aged 3 to 10.',
    },
    fr: {
      label:     'Tout',
      pageTitle: 'Pages à Colorier Gratuites pour Enfants – Imprimer & Télécharger | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites pour enfants : animaux, véhicules, princesses, saisons et plus. Téléchargez ou imprimez instantanément — 100% gratuit.',
      intro:     'Choisissez une page à colorier gratuite, cliquez sur imprimer et commencez à colorier tout de suite ! Toutes les pages conviennent aux enfants de 3 à 10 ans.',
    },
    es: {
      label:     'Todo',
      pageTitle: 'Páginas para Colorear Gratis para Niños – Imprimir & Descargar | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear gratis para niños: animales, vehículos, princesas, estaciones y más. Descarga o imprime al instante — 100% gratis.',
      intro:     'Elige una página para colorear gratis, haz clic en imprimir ¡y empieza a colorear enseguida! Todas las páginas son aptas para niños de 3 a 10 años.',
    },
    zh: {
      label:     '全部',
      pageTitle: '免费儿童涂色页 – 打印和下载 | KidsLoveColor.com',
      metaDesc:  '免费儿童涂色页：动物、交通工具、公主、四季等。立即下载或打印 — 100%免费。',
      intro:     '选择一张免费涂色页，点击打印，立即开始涂色！所有涂色页适合3至10岁儿童。',
    },
    icon: '',
  },

  dieren: {
    nl: {
      label:     'Dieren',
      pageTitle: 'Dieren Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare dieren kleurplaten voor kinderen: kat, hond, vlinder, olifant, vis, vogel en meer. Direct downloaden of afdrukken.',
      h2:        'Dieren Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten van dieren zijn altijd geliefd bij kinderen! Van schattige katten en honden tot exotische dieren uit de jungle. Allemaal gratis te printen.',
    },
    en: {
      label:     'Animals',
      pageTitle: 'Animal Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable animal coloring pages for kids: cat, dog, butterfly, elephant, fish, bird and more. Download or print instantly.',
      h2:        'Animal Coloring Pages – Free Printable',
      intro:     'Animal coloring pages are always a hit with kids! From cute cats and dogs to exotic jungle animals. All free to print.',
    },
    fr: {
      label:     'Animaux',
      pageTitle: 'Pages à Colorier Animaux pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites animaux pour enfants : chat, chien, papillon, éléphant, poisson, oiseau et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Animaux – Gratuit',
      intro:     'Les pages à colorier d\'animaux sont toujours populaires chez les enfants ! Des chats et chiens mignons aux animaux exotiques de la jungle. Tout gratuit à imprimer.',
    },
    es: {
      label:     'Animales',
      pageTitle: 'Páginas para Colorear Animales para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear animales gratis para niños: gato, perro, mariposa, elefante, pez, pájaro y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Animales – Gratis',
      intro:     '¡Las páginas para colorear de animales son siempre un éxito entre los niños! Desde gatos y perros adorables hasta animales exóticos de la jungla. Todo gratis.',
    },
    zh: {
      label:     '动物',
      pageTitle: '儿童动物涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童动物涂色页：猫、狗、蝴蝶、大象、鱼、鸟等。立即下载或打印。',
      h2:        '动物涂色页 – 免费打印',
      intro:     '动物涂色页深受儿童喜爱！从可爱的猫咪和小狗到异国丛林动物，全部免费打印。',
    },
    icon: '',
    slug_en: 'animals',
  },

  voertuigen: {
    nl: {
      label:     'Voertuigen',
      pageTitle: 'Voertuigen Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare voertuigen kleurplaten voor kinderen: auto, fiets, vliegtuig, boot en meer. Direct downloaden of afdrukken.',
      h2:        'Voertuigen Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten van voertuigen zijn perfect voor jonge verkeersliefhebbers! Auto\'s, fietsen, vliegtuigen en boten — allemaal gratis te kleuren.',
    },
    en: {
      label:     'Vehicles',
      pageTitle: 'Vehicle Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable vehicle coloring pages for kids: car, bicycle, airplane, boat and more. Download or print instantly.',
      h2:        'Vehicle Coloring Pages – Free Printable',
      intro:     'Vehicle coloring pages are perfect for young traffic enthusiasts! Cars, bikes, airplanes and boats — all free to color.',
    },
    fr: {
      label:     'Véhicules',
      pageTitle: 'Pages à Colorier Véhicules pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites véhicules pour enfants : voiture, vélo, avion, bateau et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Véhicules – Gratuit',
      intro:     'Les pages à colorier de véhicules sont parfaites pour les jeunes passionnés ! Voitures, vélos, avions et bateaux — tout gratuit à colorier.',
    },
    es: {
      label:     'Vehículos',
      pageTitle: 'Páginas para Colorear Vehículos para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear vehículos gratis para niños: coche, bicicleta, avión, barco y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Vehículos – Gratis',
      intro:     '¡Las páginas para colorear de vehículos son perfectas para los jóvenes entusiastas! Coches, bicicletas, aviones y barcos — todo gratis para colorear.',
    },
    zh: {
      label:     '交通工具',
      pageTitle: '儿童交通工具涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童交通工具涂色页：汽车、自行车、飞机、船等。立即下载或打印。',
      h2:        '交通工具涂色页 – 免费打印',
      intro:     '交通工具涂色页非常适合小交通爱好者！汽车、自行车、飞机和船 — 全部免费涂色。',
    },
    icon: '',
    slug_en: 'vehicles',
  },

  prinsessen: {
    nl: {
      label:     'Prinsessen & Feeën',
      pageTitle: 'Prinsessen Kleurplaten voor Meisjes – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare prinsessen kleurplaten voor meisjes: prinses, fee, sprookjesfiguren en meer. Direct downloaden of afdrukken.',
      h2:        'Prinsessen & Feeën Kleurplaten – Gratis Printbaar',
      intro:     'Prinsessen en feeën kleurplaten voor de echte dromerij! Schitterende prinsessen met kronen en feeën met toverstaven — gratis te printen.',
    },
    en: {
      label:     'Princesses & Fairies',
      pageTitle: 'Princess Coloring Pages for Girls – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable princess coloring pages for girls: princess, fairy, fairytale characters and more. Download or print instantly.',
      h2:        'Princess & Fairy Coloring Pages – Free Printable',
      intro:     'Princess and fairy coloring pages for true dreamers! Beautiful princesses with crowns and fairies with magic wands — all free to print.',
    },
    fr: {
      label:     'Princesses & Fées',
      pageTitle: 'Pages à Colorier Princesses pour Filles – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites princesses pour filles : princesse, fée, personnages de contes de fées et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Princesses & Fées – Gratuit',
      intro:     'Pages à colorier de princesses et de fées pour les vraies rêveuses ! De belles princesses avec des couronnes et des fées avec des baguettes magiques.',
    },
    es: {
      label:     'Princesas & Hadas',
      pageTitle: 'Páginas para Colorear Princesas para Niñas – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear princesas gratis para niñas: princesa, hada, personajes de cuentos y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Princesas & Hadas – Gratis',
      intro:     '¡Páginas para colorear de princesas y hadas para las verdaderas soñadoras! Hermosas princesas con coronas y hadas con varitas mágicas.',
    },
    zh: {
      label:     '公主与仙女',
      pageTitle: '儿童公主涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童公主涂色页：公主、仙女、童话人物等。立即下载或打印。',
      h2:        '公主与仙女涂色页 – 免费打印',
      intro:     '公主和仙女涂色页适合真正的梦想家！美丽的公主戴着皇冠，仙女挥舞着魔法棒，全部免费打印。',
    },
    icon: '',
    slug_en: 'princesses',
  },

  seizoenen: {
    nl: {
      label:     'Seizoenen & Natuur',
      pageTitle: 'Seizoenen Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare seizoenen kleurplaten voor kinderen: lente bloem, zomer zon, herfstblad, winter sneeuwpop en meer. Direct downloaden.',
      h2:        'Seizoenen & Natuur Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten over de vier seizoenen en de natuur. Van lengebloemen en zomerse zonnen tot herfstbladeren en winterse sneeuwpoppen.',
    },
    en: {
      label:     'Seasons & Nature',
      pageTitle: 'Seasonal Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable seasonal coloring pages for kids: spring flower, summer sun, autumn leaf, winter snowman and more. Download instantly.',
      h2:        'Seasons & Nature Coloring Pages – Free Printable',
      intro:     'Coloring pages about the four seasons and nature. From spring flowers and summer suns to autumn leaves and winter snowmen.',
    },
    fr: {
      label:     'Saisons & Nature',
      pageTitle: 'Pages à Colorier Saisons pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites saisons pour enfants : fleur de printemps, soleil d\'été, feuille d\'automne, bonhomme de neige et plus. Téléchargez.',
      h2:        'Pages à Colorier Saisons & Nature – Gratuit',
      intro:     'Pages à colorier sur les quatre saisons et la nature. Des fleurs du printemps aux soleils d\'été, en passant par les feuilles d\'automne et les bonshommes de neige.',
    },
    es: {
      label:     'Estaciones & Naturaleza',
      pageTitle: 'Páginas para Colorear Estaciones para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear estaciones gratis para niños: flor de primavera, sol de verano, hoja de otoño, muñeco de nieve y más. Descarga.',
      h2:        'Páginas para Colorear Estaciones & Naturaleza – Gratis',
      intro:     'Páginas para colorear sobre las cuatro estaciones y la naturaleza. Desde flores de primavera y soles de verano hasta hojas de otoño y muñecos de nieve.',
    },
    zh: {
      label:     '四季与自然',
      pageTitle: '儿童四季涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童四季涂色页：春花、夏日、秋叶、冬雪人等。立即下载或打印。',
      h2:        '四季与自然涂色页 – 免费打印',
      intro:     '关于四季和自然的涂色页。从春花、夏日到秋叶和冬雪人，应有尽有，全部免费打印。',
    },
    icon: '',
    slug_en: 'seasons',
  },

  feestdagen: {
    nl: {
      label:     'Feestdagen',
      pageTitle: 'Feestdagen Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare feestdagen kleurplaten voor kinderen: kerst, sinterklaas, pasen, halloween en meer. Direct downloaden of afdrukken.',
      h2:        'Feestdagen Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten voor elk feest! Van kerst en sinterklaas tot pasen en halloween. Perfect als activiteit tijdens de feestdagen.',
    },
    en: {
      label:     'Holidays',
      pageTitle: 'Holiday Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable holiday coloring pages for kids: Christmas, Easter, Halloween and more. Download or print instantly.',
      h2:        'Holiday Coloring Pages – Free Printable',
      intro:     'Coloring pages for every celebration! From Christmas and Easter to Halloween. Perfect as an activity during the holidays.',
    },
    fr: {
      label:     'Fêtes',
      pageTitle: 'Pages à Colorier Fêtes pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites fêtes pour enfants : Noël, Pâques, Halloween et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Fêtes – Gratuit',
      intro:     'Pages à colorier pour chaque célébration ! De Noël et Pâques à Halloween. Parfait comme activité pendant les fêtes.',
    },
    es: {
      label:     'Fiestas',
      pageTitle: 'Páginas para Colorear Fiestas para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear fiestas gratis para niños: Navidad, Pascua, Halloween y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Fiestas – Gratis',
      intro:     '¡Páginas para colorear para cada celebración! Desde Navidad y Pascua hasta Halloween. Perfectas como actividad durante las fiestas.',
    },
    zh: {
      label:     '节日',
      pageTitle: '儿童节日涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童节日涂色页：圣诞节、复活节、万圣节等。立即下载或打印。',
      h2:        '节日涂色页 – 免费打印',
      intro:     '每个节日都有涂色页！从圣诞节和复活节到万圣节。节日期间的完美涂色活动，全部免费。',
    },
    icon: '',
    slug_en: 'holidays',
  },

  eten: {
    nl: {
      label:     'Eten & Drinken',
      pageTitle: 'Eten Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare eten kleurplaten voor kinderen: fruit, groente, snoep, taarten en meer. Direct downloaden of afdrukken.',
      h2:        'Eten & Drinken Kleurplaten – Gratis Printbaar',
      intro:     'Leuke kleurplaten van eten en drinken voor kinderen. Van appels en bananen tot taarten en snoepjes.',
    },
    en: {
      label:     'Food & Drinks',
      pageTitle: 'Food Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable food coloring pages for kids: fruit, vegetables, candy, cakes and more. Download or print instantly.',
      h2:        'Food & Drink Coloring Pages – Free Printable',
      intro:     'Fun food and drink coloring pages for kids. From apples and bananas to cakes and candies.',
    },
    fr: {
      label:     'Nourriture & Boissons',
      pageTitle: 'Pages à Colorier Nourriture pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites nourriture pour enfants : fruits, légumes, bonbons, gâteaux et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Nourriture & Boissons – Gratuit',
      intro:     'Pages à colorier amusantes de nourriture et boissons pour enfants. Des pommes et bananes aux gâteaux et bonbons.',
    },
    es: {
      label:     'Comida & Bebidas',
      pageTitle: 'Páginas para Colorear Comida para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear comida gratis para niños: frutas, verduras, dulces, pasteles y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Comida & Bebidas – Gratis',
      intro:     'Divertidas páginas para colorear de comida y bebidas para niños. De manzanas y plátanos a pasteles y dulces.',
    },
    zh: {
      label:     '食物与饮料',
      pageTitle: '儿童食物涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童食物涂色页：水果、蔬菜、糖果、蛋糕等。立即下载或打印。',
      h2:        '食物与饮料涂色页 – 免费打印',
      intro:     '有趣的儿童食物和饮料涂色页。从苹果和香蕉到蛋糕和糖果，全部免费。',
    },
    icon: '',
    slug_en: 'food',
  },

  ruimte: {
    nl: {
      label:     'Ruimte',
      pageTitle: 'Ruimte Kleurplaten voor Kinderen – Gratis Printbaar | KidsLoveColor.com',
      metaDesc:  'Gratis printbare ruimte kleurplaten voor kinderen: raket, planeten, sterren, astronaut en meer. Direct downloaden of afdrukken.',
      h2:        'Ruimte Kleurplaten – Gratis Printbaar',
      intro:     'Kleurplaten over de ruimte voor kleine ruimtevaarders! Raketten, planeten, sterren en astronauten — gratis te kleuren.',
    },
    en: {
      label:     'Space',
      pageTitle: 'Space Coloring Pages for Kids – Free Printable | KidsLoveColor.com',
      metaDesc:  'Free printable space coloring pages for kids: rocket, planets, stars, astronaut and more. Download or print instantly.',
      h2:        'Space Coloring Pages – Free Printable',
      intro:     'Space coloring pages for little astronauts! Rockets, planets, stars and astronauts — all free to color.',
    },
    fr: {
      label:     'Espace',
      pageTitle: 'Pages à Colorier Espace pour Enfants – Gratuit | KidsLoveColor.com',
      metaDesc:  'Pages à colorier gratuites espace pour enfants : fusée, planètes, étoiles, astronaute et plus. Téléchargez ou imprimez.',
      h2:        'Pages à Colorier Espace – Gratuit',
      intro:     'Pages à colorier sur l\'espace pour les petits astronautes ! Fusées, planètes, étoiles et astronautes — tout gratuit à colorier.',
    },
    es: {
      label:     'Espacio',
      pageTitle: 'Páginas para Colorear Espacio para Niños – Gratis | KidsLoveColor.com',
      metaDesc:  'Páginas para colorear espacio gratis para niños: cohete, planetas, estrellas, astronauta y más. Descarga o imprime.',
      h2:        'Páginas para Colorear Espacio – Gratis',
      intro:     '¡Páginas para colorear sobre el espacio para pequeños astronautas! Cohetes, planetas, estrellas y astronautas — todo gratis para colorear.',
    },
    zh: {
      label:     '太空',
      pageTitle: '儿童太空涂色页 – 免费打印 | KidsLoveColor.com',
      metaDesc:  '免费儿童太空涂色页：火箭、行星、星星、宇航员等。立即下载或打印。',
      h2:        '太空涂色页 – 免费打印',
      intro:     '太空涂色页适合小小宇航员！火箭、行星、星星和宇航员 — 全部免费涂色。',
    },
    icon: '',
    slug_en: 'space',
  },
};

// -------------------------------------------------------
// COLORING PAGES
// -------------------------------------------------------
const COLORINGS = [

  {
    id: 17, slug: 'baby-stegosaurus', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/baby-stegosaurus.jpg',
    nl: { title: 'Baby Stegosaurus', description: 'Gratis kleurplaat van een schattige baby stegosaurus in het oerwoud. Makkelijk te kleuren voor kinderen.', keywords: 'stegosaurus kleurplaat dinosaurus baby dino gratis kinderen', altText: 'Gratis kleurplaat baby stegosaurus – kinderen' },
    en: { title: 'Baby Stegosaurus', description: 'Free coloring page of a cute baby stegosaurus in the jungle. Easy to color for children.', keywords: 'stegosaurus coloring page dinosaur baby dino free kids', altText: 'Free coloring page baby stegosaurus – kids' },
    fr: { title: 'Bébé Stégosaure', description: 'Page à colorier gratuite d\'un mignon bébé stégosaure dans la jungle. Facile à colorier pour les enfants.', keywords: 'stégosaure coloriage dinosaure bébé gratuit enfants', altText: 'Page à colorier bébé stégosaure – enfants' },
    es: { title: 'Bebé Estegosaurio', description: 'Página para colorear gratis de un bebé estegosaurio en la jungla. Fácil para niños.', keywords: 'estegosaurio colorear dinosaurio bebé gratis niños', altText: 'Colorear bebé estegosaurio – niños' },
    zh: { title: '宝宝剑龙', description: '免费儿童涂色页，画的是可爱的宝宝剑龙在丛林里。简单易涂色。', keywords: '剑龙 涂色 免费 恐龙 宝宝 儿童', altText: '免费涂色页 宝宝剑龙 – 儿童' },
  },
  {
    id: 18, slug: 'dinosaur-brontosaurus', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/dinosaur-brontosaurus.jpg',
    nl: { title: 'Brontosaurus', description: 'Gratis kleurplaat van een grote brontosaurus met palmbomen. Leuk en makkelijk voor kinderen.', keywords: 'brontosaurus kleurplaat dinosaurus palmbomen gratis kinderen', altText: 'Gratis kleurplaat brontosaurus – kinderen' },
    en: { title: 'Brontosaurus', description: 'Free coloring page of a large brontosaurus with palm trees. Fun and easy for children.', keywords: 'brontosaurus coloring page dinosaur palm trees free kids', altText: 'Free coloring page brontosaurus – kids' },
    fr: { title: 'Brontosaure', description: 'Page à colorier gratuite d\'un grand brontosaure avec des palmiers. Amusant et facile pour les enfants.', keywords: 'brontosaure coloriage dinosaure palmiers gratuit enfants', altText: 'Page à colorier brontosaure – enfants' },
    es: { title: 'Brontosaurio', description: 'Página para colorear gratis de un gran brontosaurio con palmeras. Divertido y fácil para niños.', keywords: 'brontosaurio colorear dinosaurio palmeras gratis niños', altText: 'Colorear brontosaurio – niños' },
    zh: { title: '腕龙', description: '免费儿童涂色页，画的是一只大腕龙和棕榈树。有趣简单。', keywords: '腕龙 涂色 免费 恐龙 棕榈 儿童', altText: '免费涂色页 腕龙 – 儿童' },
  },
  {
    id: 19, slug: 'cute-puppy', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/cute-puppy.jpg',
    nl: { title: 'Schattige Pup', description: 'Gratis kleurplaat van een schattige puppy met een voerbak en een botje. Perfect voor jonge kinderen.', keywords: 'puppy kleurplaat hond schattig gratis kinderen huisdier', altText: 'Gratis kleurplaat schattige pup – kinderen' },
    en: { title: 'Cute Puppy', description: 'Free coloring page of a cute puppy with a food bowl and a bone. Perfect for young children.', keywords: 'puppy coloring page dog cute free kids pet bone', altText: 'Free coloring page cute puppy – kids' },
    fr: { title: 'Mignon Chiot', description: 'Page à colorier gratuite d\'un mignon chiot avec une gamelle et un os. Parfait pour les jeunes enfants.', keywords: 'chiot coloriage chien mignon gratuit enfants os', altText: 'Page à colorier mignon chiot – enfants' },
    es: { title: 'Lindo Cachorro', description: 'Página para colorear gratis de un lindo cachorro con un tazón y un hueso. Perfecto para niños pequeños.', keywords: 'cachorro colorear perro lindo gratis niños hueso', altText: 'Colorear lindo cachorro – niños' },
    zh: { title: '可爱小狗', description: '免费儿童涂色页，画的是一只有碗和骨头的可爱小狗。很适合幼儿。', keywords: '小狗 涂色 免费 幼犬 宠物 儿童', altText: '免费涂色页 可爱小狗 – 儿童' },
  },
  {
    id: 20, slug: 'cat-rainbow', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/cat-rainbow.jpg',
    nl: { title: 'Kat met Regenboog', description: 'Gratis kleurplaat van een lieve kat met een regenboog en bloemen op de achtergrond. Vrolijk en makkelijk.', keywords: 'kat regenboog kleurplaat bloemen gratis kinderen vrolijk', altText: 'Gratis kleurplaat kat met regenboog – kinderen' },
    en: { title: 'Cat with Rainbow', description: 'Free coloring page of a sweet cat with a rainbow and flowers in the background. Cheerful and easy.', keywords: 'cat rainbow coloring page flowers free kids cheerful', altText: 'Free coloring page cat with rainbow – kids' },
    fr: { title: 'Chat avec Arc-en-ciel', description: 'Page à colorier gratuite d\'un doux chat avec un arc-en-ciel et des fleurs en arrière-plan.', keywords: 'chat arc-en-ciel coloriage fleurs gratuit enfants', altText: 'Page à colorier chat avec arc-en-ciel – enfants' },
    es: { title: 'Gato con Arcoíris', description: 'Página para colorear gratis de un dulce gato con arcoíris y flores de fondo.', keywords: 'gato arcoíris colorear flores gratis niños', altText: 'Colorear gato con arcoíris – niños' },
    zh: { title: '彩虹猫咪', description: '免费儿童涂色页，画的是有彩虹和花朵背景的可爱猫咪。', keywords: '猫 彩虹 涂色 免费 花朵 儿童', altText: '免费涂色页 彩虹猫咪 – 儿童' },
  },
  {
    id: 21, slug: 'bird-family', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/bird-family.jpg',
    nl: { title: 'Vogeltjesfamilie', description: 'Gratis kleurplaat van een lief vogelfamilietje op een tak met hartjes en bloemen. Schattig voor kinderen.', keywords: 'vogel familie kleurplaat vogeltjes tak gratis kinderen schattig', altText: 'Gratis kleurplaat vogeltjesfamilie – kinderen' },
    en: { title: 'Bird Family', description: 'Free coloring page of a sweet bird family on a branch with hearts and flowers. Adorable for kids.', keywords: 'bird family coloring page branch hearts flowers free kids', altText: 'Free coloring page bird family – kids' },
    fr: { title: 'Famille d\'Oiseaux', description: 'Page à colorier gratuite d\'une douce famille d\'oiseaux sur une branche avec des cœurs et des fleurs.', keywords: 'oiseaux famille coloriage branche cœurs gratuit enfants', altText: 'Page à colorier famille d\'oiseaux – enfants' },
    es: { title: 'Familia de Pájaros', description: 'Página para colorear gratis de una familia de pájaros en una rama con corazones y flores.', keywords: 'pájaros familia colorear rama corazones flores gratis niños', altText: 'Colorear familia de pájaros – niños' },
    zh: { title: '鸟儿一家', description: '免费儿童涂色页，画的是在树枝上的可爱鸟儿一家，有爱心和花朵。', keywords: '鸟 家庭 涂色 免费 树枝 儿童', altText: '免费涂色页 鸟儿一家 – 儿童' },
  },
  {
    id: 22, slug: 'sea-animals', category: 'dieren', difficulty: 'medium',
    img: '../img/kleurplaten/sea-animals.jpg',
    nl: { title: 'Zeedieren', description: 'Gratis kleurplaat met schattige zeedieren: walvis, dolfijn, inktvis, octopus en meer. Leuk voor kinderen.', keywords: 'zeedieren kleurplaat walvis dolfijn inktvis octopus gratis kinderen', altText: 'Gratis kleurplaat zeedieren – kinderen' },
    en: { title: 'Sea Animals', description: 'Free coloring page with cute sea animals: whale, dolphin, squid, octopus and more. Fun for kids.', keywords: 'sea animals coloring page whale dolphin squid octopus free kids', altText: 'Free coloring page sea animals – kids' },
    fr: { title: 'Animaux Marins', description: 'Page à colorier gratuite avec de mignons animaux marins : baleine, dauphin, calmar, pieuvre et plus.', keywords: 'animaux marins coloriage baleine dauphin calmar gratuit enfants', altText: 'Page à colorier animaux marins – enfants' },
    es: { title: 'Animales Marinos', description: 'Página para colorear gratis con animales marinos: ballena, delfín, calamar, pulpo y más.', keywords: 'animales marinos colorear ballena delfín calamar pulpo gratis niños', altText: 'Colorear animales marinos – niños' },
    zh: { title: '海洋动物', description: '免费儿童涂色页，有可爱的海洋动物：鲸鱼、海豚、乌贼、章鱼等。', keywords: '海洋动物 涂色 免费 鲸鱼 海豚 儿童', altText: '免费涂色页 海洋动物 – 儿童' },
  },
  {
    id: 23, slug: 'koala-tree', category: 'dieren', difficulty: 'medium',
    img: '../img/kleurplaten/koala-tree.jpg',
    nl: { title: 'Koala in de Boom', description: 'Gratis kleurplaat van een schattige koala die in een boom klimt. Mooie details voor kinderen.', keywords: 'koala kleurplaat boom klimmen gratis kinderen schattig', altText: 'Gratis kleurplaat koala in de boom – kinderen' },
    en: { title: 'Koala in a Tree', description: 'Free coloring page of a cute koala climbing a tree. Beautiful details for children.', keywords: 'koala coloring page tree climbing free kids cute', altText: 'Free coloring page koala in a tree – kids' },
    fr: { title: 'Koala dans un Arbre', description: 'Page à colorier gratuite d\'un mignon koala grimpant dans un arbre. Beaux détails pour les enfants.', keywords: 'koala arbre coloriage grimper gratuit enfants', altText: 'Page à colorier koala dans un arbre – enfants' },
    es: { title: 'Koala en un Árbol', description: 'Página para colorear gratis de un koala trepando un árbol. Bonitos detalles para niños.', keywords: 'koala árbol colorear trepar gratis niños', altText: 'Colorear koala en un árbol – niños' },
    zh: { title: '树上的考拉', description: '免费儿童涂色页，画的是一只爬树的可爱考拉。细节丰富。', keywords: '考拉 涂色 免费 树 爬树 儿童', altText: '免费涂色页 树上的考拉 – 儿童' },
  },
  {
    id: 24, slug: 'koala-boba', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/koala-boba.jpg',
    nl: { title: 'Koala met Boba Tea', description: 'Gratis kleurplaat van een lieve koala met een bubbel thee en hartjes. Super schattig voor kinderen.', keywords: 'koala boba tea kleurplaat hartjes gratis kinderen kawaii', altText: 'Gratis kleurplaat koala met boba tea – kinderen' },
    en: { title: 'Koala with Boba Tea', description: 'Free coloring page of a sweet koala with bubble tea and hearts. Super cute for kids.', keywords: 'koala boba tea coloring page hearts free kids kawaii', altText: 'Free coloring page koala with boba tea – kids' },
    fr: { title: 'Koala avec Boba Tea', description: 'Page à colorier gratuite d\'un doux koala avec du thé à bulles et des cœurs. Super mignon.', keywords: 'koala boba tea coloriage cœurs gratuit enfants kawaii', altText: 'Page à colorier koala avec boba tea – enfants' },
    es: { title: 'Koala con Boba Tea', description: 'Página para colorear gratis de un koala con té de burbujas y corazones. Super lindo.', keywords: 'koala boba tea colorear corazones gratis niños kawaii', altText: 'Colorear koala con boba tea – niños' },
    zh: { title: '考拉喝珍珠奶茶', description: '免费儿童涂色页，画的是一只喝珍珠奶茶的可爱考拉，周围有爱心。', keywords: '考拉 珍珠奶茶 涂色 免费 爱心 儿童', altText: '免费涂色页 考拉珍珠奶茶 – 儿童' },
  },
  {
    id: 25, slug: 'koala-birthday', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/koala-birthday.jpg',
    nl: { title: 'Koala Verjaardag', description: 'Gratis kleurplaat van een vrolijke koala met een feesthoedje en ballonnen voor zijn verjaardag.', keywords: 'koala verjaardag kleurplaat feest ballonnen gratis kinderen', altText: 'Gratis kleurplaat koala verjaardag – kinderen' },
    en: { title: 'Birthday Koala', description: 'Free coloring page of a happy koala with a party hat and balloons for its birthday.', keywords: 'koala birthday coloring page party hat balloons free kids', altText: 'Free coloring page birthday koala – kids' },
    fr: { title: 'Koala Anniversaire', description: 'Page à colorier gratuite d\'un koala joyeux avec un chapeau de fête et des ballons pour son anniversaire.', keywords: 'koala anniversaire coloriage chapeau ballons gratuit enfants', altText: 'Page à colorier koala anniversaire – enfants' },
    es: { title: 'Koala Cumpleaños', description: 'Página para colorear gratis de un koala feliz con sombrero de fiesta y globos para su cumpleaños.', keywords: 'koala cumpleaños colorear fiesta globos gratis niños', altText: 'Colorear koala cumpleaños – niños' },
    zh: { title: '生日考拉', description: '免费儿童涂色页，画的是戴着派对帽、手持气球庆祝生日的快乐考拉。', keywords: '考拉 生日 涂色 免费 气球 儿童', altText: '免费涂色页 生日考拉 – 儿童' },
  },
  {
    id: 26, slug: 'koala-flowers', category: 'dieren', difficulty: 'medium',
    img: '../img/kleurplaten/koala-flowers.jpg',
    nl: { title: 'Koala met Bloemen', description: 'Gratis kleurplaat van een lieve koala omringd door bloemen en bladeren op een boomstam.', keywords: 'koala bloemen kleurplaat bladeren gratis kinderen natuur', altText: 'Gratis kleurplaat koala met bloemen – kinderen' },
    en: { title: 'Koala with Flowers', description: 'Free coloring page of a sweet koala surrounded by flowers and leaves on a tree trunk.', keywords: 'koala flowers coloring page leaves nature free kids', altText: 'Free coloring page koala with flowers – kids' },
    fr: { title: 'Koala avec des Fleurs', description: 'Page à colorier gratuite d\'un doux koala entouré de fleurs et de feuilles sur un tronc d\'arbre.', keywords: 'koala fleurs coloriage feuilles nature gratuit enfants', altText: 'Page à colorier koala avec fleurs – enfants' },
    es: { title: 'Koala con Flores', description: 'Página para colorear gratis de un koala rodeado de flores y hojas sobre un tronco de árbol.', keywords: 'koala flores colorear hojas naturaleza gratis niños', altText: 'Colorear koala con flores – niños' },
    zh: { title: '花丛中的考拉', description: '免费儿童涂色页，画的是坐在树干上、被花朵和叶子环绕的可爱考拉。', keywords: '考拉 花朵 涂色 免费 叶子 儿童', altText: '免费涂色页 花丛中的考拉 – 儿童' },
  },
  {
    id: 27, slug: 'bunny-carrots', category: 'dieren', difficulty: 'easy',
    img: '../img/kleurplaten/bunny-carrots.jpg',
    nl: { title: 'Konijn met Wortels', description: 'Gratis kleurplaat van een vrolijk konijn dat wortels draagt in de tuin. Makkelijk voor kinderen.', keywords: 'konijn wortel kleurplaat tuin gratis kinderen vrolijk', altText: 'Gratis kleurplaat konijn met wortels – kinderen' },
    en: { title: 'Bunny with Carrots', description: 'Free coloring page of a cheerful bunny carrying carrots in the garden. Easy for children.', keywords: 'bunny carrot coloring page garden free kids cheerful', altText: 'Free coloring page bunny with carrots – kids' },
    fr: { title: 'Lapin avec des Carottes', description: 'Page à colorier gratuite d\'un lapin joyeux portant des carottes dans le jardin.', keywords: 'lapin carotte coloriage jardin gratuit enfants joyeux', altText: 'Page à colorier lapin avec carottes – enfants' },
    es: { title: 'Conejo con Zanahorias', description: 'Página para colorear gratis de un conejo alegre llevando zanahorias en el jardín.', keywords: 'conejo zanahoria colorear jardín gratis niños alegre', altText: 'Colorear conejo con zanahorias – niños' },
    zh: { title: '小兔子与胡萝卜', description: '免费儿童涂色页，画的是在花园里提着胡萝卜的快乐小兔子。', keywords: '兔子 胡萝卜 涂色 免费 花园 儿童', altText: '免费涂色页 小兔子与胡萝卜 – 儿童' },
  },

  // ===== NEW: KAWAII =====
  {
    id: 28, slug: 'kawaii-flowers-cactus', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-flowers-cactus.jpg',
    nl: { title: 'Kawaii Bloemen & Cactus', description: 'Gratis kawaii kleurplaat met schattige bloemen en cactussen in potjes met lieve gezichtjes.', keywords: 'kawaii bloemen cactus kleurplaat gratis kinderen schattig', altText: 'Gratis kawaii kleurplaat bloemen en cactus – kinderen' },
    en: { title: 'Kawaii Flowers & Cactus', description: 'Free kawaii coloring page with cute flowers and cacti in pots with sweet little faces.', keywords: 'kawaii flowers cactus coloring page free kids cute', altText: 'Free kawaii coloring page flowers and cactus – kids' },
    fr: { title: 'Kawaii Fleurs & Cactus', description: 'Page à colorier kawaii gratuite avec de jolies fleurs et des cactus en pots avec de petits visages.', keywords: 'kawaii fleurs cactus coloriage gratuit enfants mignon', altText: 'Page à colorier kawaii fleurs cactus – enfants' },
    es: { title: 'Kawaii Flores & Cactus', description: 'Página kawaii para colorear gratis con flores y cactus en macetas con caras adorables.', keywords: 'kawaii flores cactus colorear gratis niños lindo', altText: 'Colorear kawaii flores y cactus – niños' },
    zh: { title: '可爱花朵与仙人掌', description: '免费可爱风格涂色页，画的是有可爱小脸的花朵和盆栽仙人掌。', keywords: '可爱 花朵 仙人掌 涂色 免费 儿童', altText: '免费涂色页 可爱花朵与仙人掌 – 儿童' },
  },
  {
    id: 29, slug: 'kawaii-cactus', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-cactus.jpg',
    nl: { title: 'Kawaii Cactussen', description: 'Gratis kleurplaat met vier vrolijke kawaii cactussen in kleurrijke potjes met lieve gezichtjes.', keywords: 'kawaii cactus kleurplaat potjes gratis kinderen vrolijk', altText: 'Gratis kawaii kleurplaat cactussen – kinderen' },
    en: { title: 'Kawaii Cacti', description: 'Free coloring page with four cheerful kawaii cacti in colorful pots with sweet faces.', keywords: 'kawaii cactus coloring page pots free kids cheerful', altText: 'Free kawaii coloring page cacti – kids' },
    fr: { title: 'Cactus Kawaii', description: 'Page à colorier gratuite avec quatre joyeux cactus kawaii dans des pots colorés avec de petits visages.', keywords: 'kawaii cactus coloriage pots gratuit enfants joyeux', altText: 'Page à colorier kawaii cactus – enfants' },
    es: { title: 'Cactus Kawaii', description: 'Página para colorear gratis con cuatro alegres cactus kawaii en macetas coloridas con caritas adorables.', keywords: 'kawaii cactus colorear macetas gratis niños alegre', altText: 'Colorear kawaii cactus – niños' },
    zh: { title: '可爱仙人掌', description: '免费涂色页，画的是四个有可爱小脸的彩色盆栽仙人掌。', keywords: '可爱 仙人掌 涂色 免费 盆栽 儿童', altText: '免费涂色页 可爱仙人掌 – 儿童' },
  },
  {
    id: 30, slug: 'kawaii-cat-dog', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-cat-dog.jpg',
    nl: { title: 'Kawaii Kat & Hond', description: 'Gratis kawaii kleurplaat van een schattige kat en hond bij een hondenhok. Met vlindertjes en zon.', keywords: 'kawaii kat hond kleurplaat hondenhok gratis kinderen', altText: 'Gratis kawaii kleurplaat kat en hond – kinderen' },
    en: { title: 'Kawaii Cat & Dog', description: 'Free kawaii coloring page of a cute cat and dog at a kennel. With butterflies and sunshine.', keywords: 'kawaii cat dog coloring page kennel butterflies free kids', altText: 'Free kawaii coloring page cat and dog – kids' },
    fr: { title: 'Kawaii Chat & Chien', description: 'Page à colorier kawaii gratuite d\'un chat et d\'un chien mignons près d\'une niche. Avec papillons et soleil.', keywords: 'kawaii chat chien coloriage niche papillons gratuit enfants', altText: 'Page à colorier kawaii chat et chien – enfants' },
    es: { title: 'Kawaii Gato & Perro', description: 'Página kawaii para colorear gratis de un gato y perro junto a una casita. Con mariposas y sol.', keywords: 'kawaii gato perro colorear casita mariposas gratis niños', altText: 'Colorear kawaii gato y perro – niños' },
    zh: { title: '可爱猫咪与小狗', description: '免费可爱风格涂色页，画的是在小狗屋旁边的猫咪和小狗，有蝴蝶和阳光。', keywords: '可爱 猫 狗 涂色 免费 蝴蝶 儿童', altText: '免费涂色页 可爱猫咪与小狗 – 儿童' },
  },
  {
    id: 31, slug: 'bunny-cupcake', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/bunny-cupcake.jpg',
    nl: { title: 'Konijn op Cupcake', description: 'Gratis kawaii kleurplaat van een schattig konijn bovenop een grote cupcake met donuts.', keywords: 'konijn cupcake kleurplaat kawaii donut gratis kinderen', altText: 'Gratis kleurplaat konijn op cupcake – kinderen' },
    en: { title: 'Bunny on Cupcake', description: 'Free kawaii coloring page of a cute bunny sitting on top of a big cupcake with donuts.', keywords: 'bunny cupcake coloring page kawaii donut free kids', altText: 'Free coloring page bunny on cupcake – kids' },
    fr: { title: 'Lapin sur Cupcake', description: 'Page à colorier kawaii gratuite d\'un mignon lapin assis sur un grand cupcake avec des donuts.', keywords: 'lapin cupcake coloriage kawaii donut gratuit enfants', altText: 'Page à colorier lapin sur cupcake – enfants' },
    es: { title: 'Conejo en Cupcake', description: 'Página kawaii para colorear gratis de un conejo sentado en un gran cupcake con donuts.', keywords: 'conejo cupcake colorear kawaii donut gratis niños', altText: 'Colorear conejo en cupcake – niños' },
    zh: { title: '纸杯蛋糕上的小兔', description: '免费可爱风格涂色页，画的是坐在大纸杯蛋糕上的小兔子，周围有甜甜圈。', keywords: '兔子 纸杯蛋糕 涂色 免费 甜甜圈 儿童', altText: '免费涂色页 纸杯蛋糕上的小兔 – 儿童' },
  },
  {
    id: 32, slug: 'kawaii-sweets', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-sweets.jpg',
    nl: { title: 'Kawaii Snoepjes', description: 'Gratis kleurplaat vol kawaii snoepjes: donuts, taarten, cupcakes en ijsjes met lieve gezichtjes.', keywords: 'kawaii snoep kleurplaat donut taart cupcake ijsje gratis kinderen', altText: 'Gratis kawaii kleurplaat snoepjes – kinderen' },
    en: { title: 'Kawaii Sweets', description: 'Free coloring page full of kawaii sweets: donuts, cakes, cupcakes and ice cream with cute faces.', keywords: 'kawaii sweets coloring page donut cake cupcake ice cream free kids', altText: 'Free kawaii coloring page sweets – kids' },
    fr: { title: 'Douceurs Kawaii', description: 'Page à colorier gratuite pleine de douceurs kawaii : donuts, gâteaux, cupcakes et glaces avec de petits visages.', keywords: 'kawaii douceurs coloriage donut gâteau cupcake glace gratuit enfants', altText: 'Page à colorier kawaii douceurs – enfants' },
    es: { title: 'Dulces Kawaii', description: 'Página para colorear gratis llena de dulces kawaii: donuts, pasteles, cupcakes y helados con caritas.', keywords: 'kawaii dulces colorear donut pastel cupcake helado gratis niños', altText: 'Colorear kawaii dulces – niños' },
    zh: { title: '可爱甜点大集合', description: '免费涂色页，满满的可爱甜点：甜甜圈、蛋糕、纸杯蛋糕和冰淇淋。', keywords: '可爱 甜点 涂色 免费 蛋糕 儿童', altText: '免费涂色页 可爱甜点大集合 – 儿童' },
  },
  {
    id: 33, slug: 'kawaii-fastfood', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-fastfood.jpg',
    nl: { title: 'Kawaii Fast Food', description: 'Gratis kawaii kleurplaat met een schattige donut, hamburger en drankje met vrolijke gezichtjes.', keywords: 'kawaii fastfood kleurplaat donut hamburger drankje gratis kinderen', altText: 'Gratis kawaii kleurplaat fast food – kinderen' },
    en: { title: 'Kawaii Fast Food', description: 'Free kawaii coloring page with a cute donut, burger and drink with cheerful little faces.', keywords: 'kawaii fast food coloring page donut burger drink free kids', altText: 'Free kawaii coloring page fast food – kids' },
    fr: { title: 'Fast Food Kawaii', description: 'Page à colorier kawaii gratuite avec un mignon beignet, hamburger et boisson avec de jolis petits visages.', keywords: 'kawaii fast food coloriage beignet hamburger boisson gratuit enfants', altText: 'Page à colorier kawaii fast food – enfants' },
    es: { title: 'Fast Food Kawaii', description: 'Página kawaii para colorear gratis con un donut, hamburguesa y bebida con caritas adorables.', keywords: 'kawaii fast food colorear donut hamburguesa bebida gratis niños', altText: 'Colorear kawaii fast food – niños' },
    zh: { title: '可爱快餐', description: '免费可爱风格涂色页，画的是有可爱小脸的甜甜圈、汉堡和饮料。', keywords: '可爱 快餐 涂色 免费 汉堡 儿童', altText: '免费涂色页 可爱快餐 – 儿童' },
  },
  {
    id: 34, slug: 'kawaii-bottle-animals', category: 'kawaii', difficulty: 'medium',
    img: '../img/kleurplaten/kawaii-bottle-animals.jpg',
    nl: { title: 'Dieren in een Fles', description: 'Gratis kawaii kleurplaat van schattige kleine diertjes (konijn, beer) in een magische fles met bladeren.', keywords: 'kawaii dieren fles kleurplaat konijn beer gratis kinderen magisch', altText: 'Gratis kawaii kleurplaat dieren in fles – kinderen' },
    en: { title: 'Animals in a Bottle', description: 'Free kawaii coloring page of cute little animals (rabbit, bear) in a magic bottle with leaves.', keywords: 'kawaii animals bottle coloring page rabbit bear free kids magic', altText: 'Free kawaii coloring page animals in bottle – kids' },
    fr: { title: 'Animaux dans une Bouteille', description: 'Page à colorier kawaii gratuite de mignons petits animaux (lapin, ours) dans une bouteille magique avec des feuilles.', keywords: 'kawaii animaux bouteille coloriage lapin ours gratuit enfants magique', altText: 'Page à colorier kawaii animaux en bouteille – enfants' },
    es: { title: 'Animales en una Botella', description: 'Página kawaii para colorear gratis con animales (conejo, oso) en una botella mágica con hojas.', keywords: 'kawaii animales botella colorear conejo oso gratis niños mágico', altText: 'Colorear kawaii animales en botella – niños' },
    zh: { title: '魔法瓶中的小动物', description: '免费可爱风格涂色页，画的是在有叶子装饰的魔法瓶里的小兔子和小熊。', keywords: '可爱 动物 瓶子 涂色 免费 魔法 儿童', altText: '免费涂色页 魔法瓶中的小动物 – 儿童' },
  },
  {
    id: 35, slug: 'kawaii-fruit', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-fruit.jpg',
    nl: { title: 'Kawaii Fruit', description: 'Gratis kawaii kleurplaat met een vrolijk stel fruitjes: ananas, banaan, aardbei, watermeloen en meer.', keywords: 'kawaii fruit kleurplaat ananas banaan aardbei gratis kinderen', altText: 'Gratis kawaii kleurplaat fruit – kinderen' },
    en: { title: 'Kawaii Fruit', description: 'Free kawaii coloring page with a cheerful bunch of fruits: pineapple, banana, strawberry, watermelon and more.', keywords: 'kawaii fruit coloring page pineapple banana strawberry watermelon free kids', altText: 'Free kawaii coloring page fruit – kids' },
    fr: { title: 'Fruits Kawaii', description: 'Page à colorier kawaii gratuite avec un joyeux groupe de fruits : ananas, banane, fraise, pastèque et plus.', keywords: 'kawaii fruits coloriage ananas banane fraise pastèque gratuit enfants', altText: 'Page à colorier kawaii fruits – enfants' },
    es: { title: 'Frutas Kawaii', description: 'Página kawaii para colorear gratis con un grupo de frutas: piña, plátano, fresa, sandía y más.', keywords: 'kawaii frutas colorear piña plátano fresa sandía gratis niños', altText: 'Colorear kawaii frutas – niños' },
    zh: { title: '可爱水果派对', description: '免费可爱风格涂色页，画的是菠萝、香蕉、草莓、西瓜等一群快乐的水果。', keywords: '可爱 水果 涂色 免费 菠萝 草莓 儿童', altText: '免费涂色页 可爱水果派对 – 儿童' },
  },
  {
    id: 36, slug: 'kawaii-vegetables', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-vegetables.jpg',
    nl: { title: 'Kawaii Groenten', description: 'Gratis kawaii kleurplaat met vrolijke groenten: paprika, broccoli, wortel, ananas en meer met lieve gezichtjes.', keywords: 'kawaii groenten kleurplaat paprika broccoli wortel gratis kinderen', altText: 'Gratis kawaii kleurplaat groenten – kinderen' },
    en: { title: 'Kawaii Vegetables', description: 'Free kawaii coloring page with cheerful vegetables: pepper, broccoli, carrot and more with cute faces.', keywords: 'kawaii vegetables coloring page pepper broccoli carrot free kids', altText: 'Free kawaii coloring page vegetables – kids' },
    fr: { title: 'Légumes Kawaii', description: 'Page à colorier kawaii gratuite avec de joyeux légumes : poivron, brocoli, carotte et plus avec de petits visages.', keywords: 'kawaii légumes coloriage poivron brocoli carotte gratuit enfants', altText: 'Page à colorier kawaii légumes – enfants' },
    es: { title: 'Verduras Kawaii', description: 'Página kawaii para colorear gratis con verduras alegres: pimiento, brócoli, zanahoria y más.', keywords: 'kawaii verduras colorear pimiento brócoli zanahoria gratis niños', altText: 'Colorear kawaii verduras – niños' },
    zh: { title: '可爱蔬菜', description: '免费可爱风格涂色页，画的是有可爱小脸的辣椒、西兰花、胡萝卜等蔬菜。', keywords: '可爱 蔬菜 涂色 免费 胡萝卜 儿童', altText: '免费涂色页 可爱蔬菜 – 儿童' },
  },
  {
    id: 37, slug: 'kawaii-burgers', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-burgers.jpg',
    nl: { title: 'Kawaii Hamburgers', description: 'Gratis kawaii kleurplaat met grappige hamburgers, frietjes en een smoothie met gezichtjes.', keywords: 'kawaii hamburger frietjes kleurplaat gratis kinderen smoothie', altText: 'Gratis kawaii kleurplaat hamburgers – kinderen' },
    en: { title: 'Kawaii Burgers', description: 'Free kawaii coloring page with funny burgers, fries and a smoothie with cute faces.', keywords: 'kawaii burger fries coloring page smoothie free kids', altText: 'Free kawaii coloring page burgers – kids' },
    fr: { title: 'Hamburgers Kawaii', description: 'Page à colorier kawaii gratuite avec des hamburgers rigolos, des frites et un smoothie avec des visages.', keywords: 'kawaii hamburger frites coloriage smoothie gratuit enfants', altText: 'Page à colorier kawaii hamburgers – enfants' },
    es: { title: 'Hamburguesas Kawaii', description: 'Página kawaii para colorear gratis con hamburguesas, papas fritas y un batido con caritas.', keywords: 'kawaii hamburguesa papas fritas colorear batido gratis niños', altText: 'Colorear kawaii hamburguesas – niños' },
    zh: { title: '可爱汉堡', description: '免费可爱风格涂色页，画的是有可爱小脸的汉堡、薯条和奶昔。', keywords: '可爱 汉堡 薯条 涂色 免费 儿童', altText: '免费涂色页 可爱汉堡 – 儿童' },
  },
  {
    id: 38, slug: 'kawaii-ice-cream', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-ice-cream.jpg',
    nl: { title: 'Kawaii IJsjes', description: 'Gratis kawaii kleurplaat met een schattig ijslolly en een hoorntje met lieve gezichtjes en hartjes.', keywords: 'kawaii ijsje kleurplaat ijslolly hoorntje gratis kinderen hartjes', altText: 'Gratis kawaii kleurplaat ijsjes – kinderen' },
    en: { title: 'Kawaii Ice Cream', description: 'Free kawaii coloring page with a cute popsicle and ice cream cone with sweet faces and hearts.', keywords: 'kawaii ice cream coloring page popsicle cone hearts free kids', altText: 'Free kawaii coloring page ice cream – kids' },
    fr: { title: 'Glaces Kawaii', description: 'Page à colorier kawaii gratuite avec une mignonne glace à l\'eau et un cornet avec des petits visages et des cœurs.', keywords: 'kawaii glace coloriage esquimau cornet cœurs gratuit enfants', altText: 'Page à colorier kawaii glaces – enfants' },
    es: { title: 'Helados Kawaii', description: 'Página kawaii para colorear gratis con un palito y un cono de helado con caritas adorables y corazones.', keywords: 'kawaii helado colorear palito cono corazones gratis niños', altText: 'Colorear kawaii helados – niños' },
    zh: { title: '可爱冰淇淋', description: '免费可爱风格涂色页，画的是有可爱小脸和爱心的冰棒和冰淇淋甜筒。', keywords: '可爱 冰淇淋 涂色 免费 爱心 儿童', altText: '免费涂色页 可爱冰淇淋 – 儿童' },
  },
  {
    id: 39, slug: 'kawaii-desserts', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-desserts.jpg',
    nl: { title: 'Kawaii Desserts', description: 'Gratis kawaii kleurplaat vol lekkere desserts: glaasjes met mousse, ijsjes, cupcakes en taartjes.', keywords: 'kawaii desserts kleurplaat mousse cupcake taartje ijsje gratis kinderen', altText: 'Gratis kawaii kleurplaat desserts – kinderen' },
    en: { title: 'Kawaii Desserts', description: 'Free kawaii coloring page full of delicious desserts: mousse glasses, ice cream, cupcakes and little cakes.', keywords: 'kawaii desserts coloring page mousse cupcake cake ice cream free kids', altText: 'Free kawaii coloring page desserts – kids' },
    fr: { title: 'Desserts Kawaii', description: 'Page à colorier kawaii gratuite pleine de délicieux desserts : verres de mousse, glaces, cupcakes et petits gâteaux.', keywords: 'kawaii desserts coloriage mousse cupcake gâteau glace gratuit enfants', altText: 'Page à colorier kawaii desserts – enfants' },
    es: { title: 'Postres Kawaii', description: 'Página kawaii para colorear gratis llena de postres deliciosos: copas de mousse, helados, cupcakes y pasteles.', keywords: 'kawaii postres colorear mousse cupcake pastel helado gratis niños', altText: 'Colorear kawaii postres – niños' },
    zh: { title: '可爱甜品', description: '免费可爱风格涂色页，满满的美味甜品：慕斯杯、冰淇淋、纸杯蛋糕和小蛋糕。', keywords: '可爱 甜品 涂色 免费 蛋糕 冰淇淋 儿童', altText: '免费涂色页 可爱甜品 – 儿童' },
  },
  {
    id: 40, slug: 'kawaii-cat-ice-cream', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-cat-ice-cream.jpg',
    nl: { title: 'Kat met IJsje', description: 'Gratis kawaii kleurplaat van een schattige kat die een ijsje vasthoudt, omringd door hartjes en sterren.', keywords: 'kawaii kat ijsje kleurplaat hartjes sterren gratis kinderen', altText: 'Gratis kawaii kleurplaat kat met ijsje – kinderen' },
    en: { title: 'Cat with Ice Cream', description: 'Free kawaii coloring page of a cute cat holding an ice cream, surrounded by hearts and stars.', keywords: 'kawaii cat ice cream coloring page hearts stars free kids', altText: 'Free kawaii coloring page cat with ice cream – kids' },
    fr: { title: 'Chat avec une Glace', description: 'Page à colorier kawaii gratuite d\'un mignon chat tenant une glace, entouré de cœurs et d\'étoiles.', keywords: 'kawaii chat glace coloriage cœurs étoiles gratuit enfants', altText: 'Page à colorier kawaii chat avec glace – enfants' },
    es: { title: 'Gato con Helado', description: 'Página kawaii para colorear gratis de un gato sosteniendo un helado, rodeado de corazones y estrellas.', keywords: 'kawaii gato helado colorear corazones estrellas gratis niños', altText: 'Colorear kawaii gato con helado – niños' },
    zh: { title: '拿冰淇淋的猫咪', description: '免费可爱风格涂色页，画的是手拿冰淇淋、被爱心和星星围绕的可爱猫咪。', keywords: '可爱 猫 冰淇淋 涂色 免费 爱心 儿童', altText: '免费涂色页 拿冰淇淋的猫咪 – 儿童' },
  },
  {
    id: 41, slug: 'kawaii-pizza', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-pizza.jpg',
    nl: { title: 'Kawaii Pizza & Friends', description: 'Gratis kawaii kleurplaat met pizza, hotdog, hamburger, frietjes en een ijsje met vrolijke gezichtjes.', keywords: 'kawaii pizza hotdog hamburger frietjes kleurplaat gratis kinderen', altText: 'Gratis kawaii kleurplaat pizza en vrienden – kinderen' },
    en: { title: 'Kawaii Pizza & Friends', description: 'Free kawaii coloring page with pizza, hot dog, burger, fries and ice cream with cheerful faces.', keywords: 'kawaii pizza hot dog burger fries coloring page free kids', altText: 'Free kawaii coloring page pizza and friends – kids' },
    fr: { title: 'Kawaii Pizza & Amis', description: 'Page à colorier kawaii gratuite avec pizza, hot-dog, hamburger, frites et glace avec des visages joyeux.', keywords: 'kawaii pizza hot-dog hamburger frites coloriage gratuit enfants', altText: 'Page à colorier kawaii pizza et amis – enfants' },
    es: { title: 'Kawaii Pizza & Amigos', description: 'Página kawaii para colorear gratis con pizza, hot dog, hamburguesa, papas fritas y helado.', keywords: 'kawaii pizza hot dog hamburguesa papas fritas colorear gratis niños', altText: 'Colorear kawaii pizza y amigos – niños' },
    zh: { title: '可爱披萨伙伴', description: '免费可爱风格涂色页，画的是有可爱小脸的披萨、热狗、汉堡、薯条和冰淇淋。', keywords: '可爱 披萨 热狗 汉堡 涂色 免费 儿童', altText: '免费涂色页 可爱披萨伙伴 – 儿童' },
  },
  {
    id: 42, slug: 'kawaii-plants', category: 'kawaii', difficulty: 'medium',
    img: '../img/kleurplaten/kawaii-plants.jpg',
    nl: { title: 'Kawaii Plantjes', description: 'Gratis kawaii kleurplaat met schattige planten, bloemen en een cactus met gezichtjes en hartjes.', keywords: 'kawaii planten bloemen cactus kleurplaat gratis kinderen hartjes', altText: 'Gratis kawaii kleurplaat plantjes – kinderen' },
    en: { title: 'Kawaii Plants', description: 'Free kawaii coloring page with cute plants, flowers and a cactus with little faces and hearts.', keywords: 'kawaii plants flowers cactus coloring page hearts free kids', altText: 'Free kawaii coloring page plants – kids' },
    fr: { title: 'Plantes Kawaii', description: 'Page à colorier kawaii gratuite avec de mignonnes plantes, fleurs et un cactus avec des petits visages et cœurs.', keywords: 'kawaii plantes fleurs cactus coloriage cœurs gratuit enfants', altText: 'Page à colorier kawaii plantes – enfants' },
    es: { title: 'Plantas Kawaii', description: 'Página kawaii para colorear gratis con plantas, flores y un cactus con caritas y corazones.', keywords: 'kawaii plantas flores cactus colorear corazones gratis niños', altText: 'Colorear kawaii plantas – niños' },
    zh: { title: '可爱小植物', description: '免费可爱风格涂色页，画的是有可爱小脸和爱心的植物、花朵和仙人掌。', keywords: '可爱 植物 花朵 仙人掌 涂色 免费 儿童', altText: '免费涂色页 可爱小植物 – 儿童' },
  },
  {
    id: 43, slug: 'kawaii-school', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-school.jpg',
    nl: { title: 'Kawaii School', description: 'Gratis kawaii kleurplaat met schattige schoolspullen: rugzak, notitieboek, klok, potlood en globe.', keywords: 'kawaii school kleurplaat rugzak notitieboek potlood gratis kinderen', altText: 'Gratis kawaii kleurplaat schoolspullen – kinderen' },
    en: { title: 'Kawaii School', description: 'Free kawaii coloring page with cute school supplies: backpack, notebook, clock, pencil and globe.', keywords: 'kawaii school coloring page backpack notebook pencil globe free kids', altText: 'Free kawaii coloring page school – kids' },
    fr: { title: 'École Kawaii', description: 'Page à colorier kawaii gratuite avec de mignonnes fournitures scolaires : sac à dos, carnet, horloge, crayon et globe.', keywords: 'kawaii école coloriage sac à dos carnet crayon globe gratuit enfants', altText: 'Page à colorier kawaii école – enfants' },
    es: { title: 'Escuela Kawaii', description: 'Página kawaii para colorear gratis con útiles escolares: mochila, cuaderno, reloj, lápiz y globo terráqueo.', keywords: 'kawaii escuela colorear mochila cuaderno lápiz globo gratis niños', altText: 'Colorear kawaii escuela – niños' },
    zh: { title: '可爱学校用品', description: '免费可爱风格涂色页，画的是书包、笔记本、时钟、铅笔和地球仪等学校用品。', keywords: '可爱 学校 书包 铅笔 涂色 免费 儿童', altText: '免费涂色页 可爱学校用品 – 儿童' },
  },
  {
    id: 44, slug: 'kawaii-smoothie', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-smoothie.jpg',
    nl: { title: 'Kawaii Smoothie', description: 'Gratis kawaii kleurplaat van een grote smoothie omringd door vrolijke fruitjes met lieve gezichtjes.', keywords: 'kawaii smoothie kleurplaat fruit gratis kinderen schattig', altText: 'Gratis kawaii kleurplaat smoothie – kinderen' },
    en: { title: 'Kawaii Smoothie', description: 'Free kawaii coloring page of a big smoothie surrounded by cheerful fruits with cute little faces.', keywords: 'kawaii smoothie coloring page fruit free kids cute', altText: 'Free kawaii coloring page smoothie – kids' },
    fr: { title: 'Smoothie Kawaii', description: 'Page à colorier kawaii gratuite d\'un grand smoothie entouré de joyeux fruits avec de petits visages.', keywords: 'kawaii smoothie coloriage fruits gratuit enfants mignon', altText: 'Page à colorier kawaii smoothie – enfants' },
    es: { title: 'Smoothie Kawaii', description: 'Página kawaii para colorear gratis de un gran smoothie rodeado de frutas alegres con caritas adorables.', keywords: 'kawaii smoothie colorear frutas gratis niños lindo', altText: 'Colorear kawaii smoothie – niños' },
    zh: { title: '可爱奶昔', description: '免费可爱风格涂色页，画的是被有可爱小脸的水果围绕的大奶昔。', keywords: '可爱 奶昔 水果 涂色 免费 儿童', altText: '免费涂色页 可爱奶昔 – 儿童' },
  },
  {
    id: 45, slug: 'kawaii-cake', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-cake.jpg',
    nl: { title: 'Kawaii Taart Feest', description: 'Gratis kawaii kleurplaat van een grote taart met snoepjes, ijsjes en allerlei andere lekkernijen.', keywords: 'kawaii taart feest kleurplaat snoep ijsje gratis kinderen', altText: 'Gratis kawaii kleurplaat taart feest – kinderen' },
    en: { title: 'Kawaii Cake Party', description: 'Free kawaii coloring page of a big cake with candies, ice cream and all kinds of other treats.', keywords: 'kawaii cake party coloring page candy ice cream free kids', altText: 'Free kawaii coloring page cake party – kids' },
    fr: { title: 'Fête des Gâteaux Kawaii', description: 'Page à colorier kawaii gratuite d\'un grand gâteau avec des bonbons, des glaces et toutes sortes de friandises.', keywords: 'kawaii gâteau fête coloriage bonbons glace gratuit enfants', altText: 'Page à colorier kawaii fête gâteau – enfants' },
    es: { title: 'Fiesta de Pasteles Kawaii', description: 'Página kawaii para colorear gratis de un gran pastel con dulces, helados y todo tipo de golosinas.', keywords: 'kawaii pastel fiesta colorear dulces helados gratis niños', altText: 'Colorear kawaii fiesta de pasteles – niños' },
    zh: { title: '可爱蛋糕派对', description: '免费可爱风格涂色页，画的是有糖果、冰淇淋等各种美食的大蛋糕。', keywords: '可爱 蛋糕 派对 涂色 免费 糖果 儿童', altText: '免费涂色页 可爱蛋糕派对 – 儿童' },
  },
  {
    id: 46, slug: 'bunny-teacup', category: 'kawaii', difficulty: 'easy',
    img: '../img/kleurplaten/bunny-teacup.jpg',
    nl: { title: 'Konijn in Theekopje', description: 'Gratis kawaii kleurplaat van een schattig konijn dat in een groot theekopje zit met bloemen en hartjes.', keywords: 'kawaii konijn theekopje kleurplaat bloemen hartjes gratis kinderen', altText: 'Gratis kawaii kleurplaat konijn in theekopje – kinderen' },
    en: { title: 'Bunny in Teacup', description: 'Free kawaii coloring page of a cute bunny sitting in a big teacup with flowers and hearts.', keywords: 'kawaii bunny teacup coloring page flowers hearts free kids', altText: 'Free kawaii coloring page bunny in teacup – kids' },
    fr: { title: 'Lapin dans une Tasse', description: 'Page à colorier kawaii gratuite d\'un mignon lapin assis dans une grande tasse de thé avec des fleurs et des cœurs.', keywords: 'kawaii lapin tasse thé coloriage fleurs cœurs gratuit enfants', altText: 'Page à colorier kawaii lapin dans une tasse – enfants' },
    es: { title: 'Conejo en Taza de Té', description: 'Página kawaii para colorear gratis de un conejo sentado en una gran taza de té con flores y corazones.', keywords: 'kawaii conejo taza té colorear flores corazones gratis niños', altText: 'Colorear kawaii conejo en taza de té – niños' },
    zh: { title: '茶杯里的小兔', description: '免费可爱风格涂色页，画的是坐在大茶杯里、周围有花朵和爱心的可爱小兔子。', keywords: '可爱 兔子 茶杯 涂色 免费 爱心 儿童', altText: '免费涂色页 茶杯里的小兔 – 儿童' },
  },

  // ===== NEW: NATUUR / NATURE =====
  {
    id: 47, slug: 'kawaii-flowers-sun', category: 'natuur', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-flowers-sun.jpg',
    nl: { title: 'Bloemen & Zon', description: 'Gratis kawaii kleurplaat van een lieve zon omringd door mooie bloemen en een bijtje. Kleurrijk en vrolijk.', keywords: 'bloemen zon kleurplaat kawaii bij gratis kinderen lente', altText: 'Gratis kawaii kleurplaat bloemen en zon – kinderen' },
    en: { title: 'Flowers & Sun', description: 'Free kawaii coloring page of a sweet sun surrounded by beautiful flowers and a little bee. Colorful and cheerful.', keywords: 'flowers sun coloring page kawaii bee free kids spring', altText: 'Free kawaii coloring page flowers and sun – kids' },
    fr: { title: 'Fleurs & Soleil', description: 'Page à colorier kawaii gratuite d\'un doux soleil entouré de belles fleurs et d\'une petite abeille. Coloré et joyeux.', keywords: 'fleurs soleil coloriage kawaii abeille gratuit enfants printemps', altText: 'Page à colorier kawaii fleurs et soleil – enfants' },
    es: { title: 'Flores & Sol', description: 'Página kawaii para colorear gratis de un dulce sol rodeado de hermosas flores y una abejita.', keywords: 'flores sol colorear kawaii abeja gratis niños primavera', altText: 'Colorear kawaii flores y sol – niños' },
    zh: { title: '花朵与太阳', description: '免费可爱风格涂色页，画的是被美丽花朵和小蜜蜂环绕的可爱太阳。', keywords: '花朵 太阳 涂色 免费 蜜蜂 儿童 春天', altText: '免费涂色页 花朵与太阳 – 儿童' },
  },
  {
    id: 48, slug: 'kawaii-mushrooms', category: 'natuur', difficulty: 'easy',
    img: '../img/kleurplaten/kawaii-mushrooms.jpg',
    nl: { title: 'Kawaii Paddenstoelen', description: 'Gratis kawaii kleurplaat van een grote groep vrolijke paddenstoelen met lieve gezichtjes in het bos.', keywords: 'kawaii paddenstoelen kleurplaat bos gratis kinderen vrolijk', altText: 'Gratis kawaii kleurplaat paddenstoelen – kinderen' },
    en: { title: 'Kawaii Mushrooms', description: 'Free kawaii coloring page of a large group of cheerful mushrooms with cute faces in the forest.', keywords: 'kawaii mushrooms coloring page forest free kids cheerful', altText: 'Free kawaii coloring page mushrooms – kids' },
    fr: { title: 'Champignons Kawaii', description: 'Page à colorier kawaii gratuite d\'un grand groupe de champignons joyeux avec de petits visages dans la forêt.', keywords: 'kawaii champignons coloriage forêt gratuit enfants joyeux', altText: 'Page à colorier kawaii champignons – enfants' },
    es: { title: 'Setas Kawaii', description: 'Página kawaii para colorear gratis de un gran grupo de setas alegres con caritas en el bosque.', keywords: 'kawaii setas hongos colorear bosque gratis niños alegre', altText: 'Colorear kawaii setas – niños' },
    zh: { title: '可爱蘑菇家族', description: '免费可爱风格涂色页，画的是森林里一群有可爱小脸的快乐蘑菇。', keywords: '可爱 蘑菇 涂色 免费 森林 儿童', altText: '免费涂色页 可爱蘑菇家族 – 儿童' },
  },
  {
    id: 49, slug: 'kawaii-mushroom-scene', category: 'natuur', difficulty: 'medium',
    img: '../img/kleurplaten/kawaii-mushroom-scene.jpg',
    nl: { title: 'Paddenstoelen Tafereel', description: 'Gratis kawaii kleurplaat met schattige paddenstoelen, bladeren en kleine wezentjes in een magisch boslandschap.', keywords: 'paddenstoelen kawaii kleurplaat bos magisch gratis kinderen', altText: 'Gratis kawaii kleurplaat paddenstoelen tafereel – kinderen' },
    en: { title: 'Mushroom Scene', description: 'Free kawaii coloring page with cute mushrooms, leaves and little creatures in a magical forest landscape.', keywords: 'kawaii mushroom scene coloring page forest magical free kids', altText: 'Free kawaii coloring page mushroom scene – kids' },
    fr: { title: 'Scène de Champignons', description: 'Page à colorier kawaii gratuite avec de mignons champignons, des feuilles et de petites créatures dans un paysage forestier magique.', keywords: 'kawaii champignons scène coloriage forêt magique gratuit enfants', altText: 'Page à colorier kawaii scène champignons – enfants' },
    es: { title: 'Escena de Setas', description: 'Página kawaii para colorear gratis con setas, hojas y pequeñas criaturas en un paisaje forestal mágico.', keywords: 'kawaii setas escena colorear bosque mágico gratis niños', altText: 'Colorear kawaii escena de setas – niños' },
    zh: { title: '蘑菇森林', description: '免费可爱风格涂色页，画的是有蘑菇、叶子和小生物的魔法森林场景。', keywords: '可爱 蘑菇 森林 涂色 免费 魔法 儿童', altText: '免费涂色页 蘑菇森林 – 儿童' },
  },

  // ===== NEW: RUIMTE / SPACE =====
  {
    id: 50, slug: 'kawaii-space', category: 'ruimte', difficulty: 'medium',
    img: '../img/kleurplaten/kawaii-space.jpg',
    nl: { title: 'Kawaii Ruimte', description: 'Gratis kawaii kleurplaat met een schattige astronaut, raket, UFO, planeet en vallende sterren.', keywords: 'kawaii ruimte kleurplaat astronaut raket UFO planeet gratis kinderen', altText: 'Gratis kawaii kleurplaat ruimte – kinderen' },
    en: { title: 'Kawaii Space', description: 'Free kawaii coloring page with a cute astronaut, rocket, UFO, planet and shooting stars.', keywords: 'kawaii space coloring page astronaut rocket UFO planet free kids', altText: 'Free kawaii coloring page space – kids' },
    fr: { title: 'Espace Kawaii', description: 'Page à colorier kawaii gratuite avec un mignon astronaute, une fusée, une soucoupe volante, une planète et des étoiles filantes.', keywords: 'kawaii espace coloriage astronaute fusée OVNI planète gratuit enfants', altText: 'Page à colorier kawaii espace – enfants' },
    es: { title: 'Espacio Kawaii', description: 'Página kawaii para colorear gratis con un astronauta, cohete, OVNI, planeta y estrellas fugaces.', keywords: 'kawaii espacio colorear astronauta cohete OVNI planeta gratis niños', altText: 'Colorear kawaii espacio – niños' },
    zh: { title: '可爱太空', description: '免费可爱风格涂色页，画的是可爱的宇航员、火箭、UFO、星球和流星。', keywords: '可爱 太空 宇航员 火箭 涂色 免费 儿童', altText: '免费涂色页 可爱太空 – 儿童' },
  },

  // ===== NEW: SPROOKJES / FAIRY TALES =====
  {
    id: 51, slug: 'unicorn-hearts', category: 'sprookjes', difficulty: 'easy',
    img: '../img/kleurplaten/unicorn-hearts.jpg',
    nl: { title: 'Eenhoorn met Hartjes', description: 'Gratis kleurplaat van een vrolijke eenhoorn die springt tussen hartjes en wolkjes. Super schattig!', keywords: 'eenhoorn hartjes kleurplaat gratis kinderen sprookje schattig', altText: 'Gratis kleurplaat eenhoorn met hartjes – kinderen' },
    en: { title: 'Unicorn with Hearts', description: 'Free coloring page of a cheerful unicorn jumping between hearts and clouds. Super cute!', keywords: 'unicorn hearts coloring page free kids fairy tale cute', altText: 'Free coloring page unicorn with hearts – kids' },
    fr: { title: 'Licorne avec des Cœurs', description: 'Page à colorier gratuite d\'une joyeuse licorne sautant entre des cœurs et des nuages. Super mignon !', keywords: 'licorne cœurs coloriage gratuit enfants conte fée mignon', altText: 'Page à colorier licorne avec cœurs – enfants' },
    es: { title: 'Unicornio con Corazones', description: 'Página para colorear gratis de un unicornio saltando entre corazones y nubes. ¡Super lindo!', keywords: 'unicornio corazones colorear gratis niños cuento hada lindo', altText: 'Colorear unicornio con corazones – niños' },
    zh: { title: '爱心独角兽', description: '免费儿童涂色页，画的是在爱心和云朵间跳跃的快乐独角兽。超级可爱！', keywords: '独角兽 爱心 涂色 免费 童话 儿童', altText: '免费涂色页 爱心独角兽 – 儿童' },
  },
  {
    id: 52, slug: 'unicorn-cloud-stars', category: 'sprookjes', difficulty: 'easy',
    img: '../img/kleurplaten/unicorn-cloud-stars.jpg',
    nl: { title: 'Eenhoorn op Wolk', description: 'Gratis kleurplaat van een dromerige eenhoorn op een wolk, omringd door sterren. Rustgevend en mooi.', keywords: 'eenhoorn wolk sterren kleurplaat gratis kinderen dromerig', altText: 'Gratis kleurplaat eenhoorn op wolk – kinderen' },
    en: { title: 'Unicorn on a Cloud', description: 'Free coloring page of a dreamy unicorn on a cloud, surrounded by stars. Calming and beautiful.', keywords: 'unicorn cloud stars coloring page free kids dreamy', altText: 'Free coloring page unicorn on cloud – kids' },
    fr: { title: 'Licorne sur un Nuage', description: 'Page à colorier gratuite d\'une licorne rêveuse sur un nuage, entourée d\'étoiles. Apaisant et magnifique.', keywords: 'licorne nuage étoiles coloriage gratuit enfants rêveur', altText: 'Page à colorier licorne sur un nuage – enfants' },
    es: { title: 'Unicornio en una Nube', description: 'Página para colorear gratis de un unicornio soñador en una nube, rodeado de estrellas.', keywords: 'unicornio nube estrellas colorear gratis niños soñador', altText: 'Colorear unicornio en una nube – niños' },
    zh: { title: '云朵上的独角兽', description: '免费儿童涂色页，画的是站在云朵上、被星星围绕的梦幻独角兽。', keywords: '独角兽 云朵 星星 涂色 免费 儿童', altText: '免费涂色页 云朵上的独角兽 – 儿童' },
  },
  {
    id: 53, slug: 'unicorn-rainbow-cute', category: 'sprookjes', difficulty: 'easy',
    img: '../img/kleurplaten/unicorn-rainbow-cute.jpg',
    nl: { title: 'Schattige Eenhoorn', description: 'Gratis kleurplaat van een superschattige kleine eenhoorn met grote ogen en een regenboog.', keywords: 'eenhoorn regenboog kleurplaat schattig gratis kinderen groot ogen', altText: 'Gratis kleurplaat schattige eenhoorn met regenboog – kinderen' },
    en: { title: 'Cute Little Unicorn', description: 'Free coloring page of a super cute little unicorn with big eyes and a rainbow behind it.', keywords: 'unicorn rainbow coloring page cute big eyes free kids', altText: 'Free coloring page cute little unicorn – kids' },
    fr: { title: 'Mignonne Licorne', description: 'Page à colorier gratuite d\'une super mignonne petite licorne avec de grands yeux et un arc-en-ciel.', keywords: 'licorne arc-en-ciel coloriage mignonne gratuit enfants', altText: 'Page à colorier mignonne licorne – enfants' },
    es: { title: 'Lindo Unicornio', description: 'Página para colorear gratis de un lindo pequeño unicornio con ojos grandes y un arcoíris detrás.', keywords: 'unicornio arcoíris colorear lindo ojos grandes gratis niños', altText: 'Colorear lindo unicornio – niños' },
    zh: { title: '可爱小独角兽', description: '免费儿童涂色页，画的是有大眼睛和彩虹背景的超级可爱小独角兽。', keywords: '独角兽 彩虹 涂色 免费 可爱 儿童', altText: '免费涂色页 可爱小独角兽 – 儿童' },
  },
  {
    id: 54, slug: 'unicorn-rainbow', category: 'sprookjes', difficulty: 'medium',
    img: '../img/kleurplaten/unicorn-rainbow.jpg',
    nl: { title: 'Eenhoorn & Regenboog', description: 'Gratis kleurplaat van een mooie eenhoorn voor een grote regenboog met sterren en wolkjes. Gedetailleerd en prachtig.', keywords: 'eenhoorn regenboog kleurplaat sterren wolkjes gratis kinderen', altText: 'Gratis kleurplaat eenhoorn en regenboog – kinderen' },
    en: { title: 'Unicorn & Rainbow', description: 'Free coloring page of a beautiful unicorn in front of a large rainbow with stars and clouds. Detailed and stunning.', keywords: 'unicorn rainbow coloring page stars clouds free kids beautiful', altText: 'Free coloring page unicorn and rainbow – kids' },
    fr: { title: 'Licorne & Arc-en-ciel', description: 'Page à colorier gratuite d\'une belle licorne devant un grand arc-en-ciel avec des étoiles et des nuages.', keywords: 'licorne arc-en-ciel coloriage étoiles nuages gratuit enfants beau', altText: 'Page à colorier licorne et arc-en-ciel – enfants' },
    es: { title: 'Unicornio & Arcoíris', description: 'Página para colorear gratis de un hermoso unicornio frente a un gran arcoíris con estrellas y nubes.', keywords: 'unicornio arcoíris colorear estrellas nubes gratis niños hermoso', altText: 'Colorear unicornio y arcoíris – niños' },
    zh: { title: '独角兽与彩虹', description: '免费儿童涂色页，画的是站在大彩虹前的美丽独角兽，有星星和云朵。', keywords: '独角兽 彩虹 涂色 免费 星星 儿童', altText: '免费涂色页 独角兽与彩虹 – 儿童' },
  },

];
