/*
 * Verhalenarchief voor "Vandaag op Aarde".
 *
 * Nieuwe edities bovenaan toevoegen. Een kleurplaat is optioneel:
 * laat coloringSlug weg totdat de bijpassende tekening klaarstaat.
 */
const WORLD_STORY_EDITIONS = [
  {
    published: '2026-08-29',
    stories: [
      {
        slug: 'kew-bespaart-fossiele-brandstof',
        title: 'Kew bespaart in één jaar 22% fossiele brandstof',
        location: 'Londen, Verenigd Koninkrijk',
        reportedDate: '26 augustus 2026',
        theme: 'Klimaat & planten',
        icon: '♨',
        intro: 'Royal Botanic Gardens, Kew gebruikte in één jaar 22% minder fossiele brandstof. Warmtepompen, elektrische machines en zonnepanelen helpen de beroemde tuinen steeds klimaatvriendelijker te werken.',
        body: 'Kew maakte bekend dat het gebruik van fossiele brandstoffen tussen 2025 en 2026 met 22% daalde en de kernuitstoot met 17%. De grootste nog bestaande Victoriaanse kas ter wereld, de Temperate House, wordt nu zonder gas verwarmd met lucht-waterwarmtepompen. Ook vervangt Kew voertuigen en tuingereedschap door elektrische versies. Op het Millennium Seed Bank-gebouw liggen zonnepanelen die ongeveer een vijfde van de elektriciteit van dat gebouw leveren. Zo beschermt Kew planten én verkleint het de eigen voetafdruk.',
        facts: [
          'Het gebruik van fossiele brandstoffen daalde in één jaar met 22%.',
          'De Temperate House wordt verwarmd met elektrische lucht-waterwarmtepompen.',
          'Kew wil in 2030 klimaatpositief zijn.',
        ],
        question: 'Welke verandering zou jouw school of buurt kunnen helpen om minder fossiele brandstof te gebruiken?',
        sourceLabel: 'Royal Botanic Gardens, Kew',
        sourceUrl: 'https://www.kew.org/about-us/press-media/kew-reduces-fossil-fuel-consumption',
        referenceUrl: '/img/vandaag-op-aarde/references/2026-08-29/kew-palm-house.jpg',
        coloringSlug: 'kew-gardens-heat-pump-climate-positive',
      },
      {
        slug: 'kunst-van-afval-op-bergpad',
        title: 'Afval verandert in kunst op een bergpad',
        location: 'China',
        reportedDate: '26 augustus 2026',
        theme: 'Kunst & klimaat',
        icon: '♻',
        intro: 'Een Chinees kunstproject veranderde opgeruimd afval uit de bergen in twaalf kleine kunstwerken langs een wandelpad van 2,5 kilometer.',
        body: 'Tijdens UNESCO’s Art for Earth-webinar liet kunstenaar Lan Qixia zien hoe jongeren en buurtvrijwilligers samen bergafval verzamelden, schoonmaakten en opnieuw gebruikten. Van takjes, blikjes, flessen en verpakkingen maakten ze kleine installaties tussen de bomen. De kunstwerken laten wandelaars nadenken over afval, verantwoordelijkheid en hun band met de natuur. Het project laat zien dat kunst niet alleen mooi kan zijn, maar ook een gesprek kan beginnen over hoe mensen voor een landschap zorgen.',
        facts: [
          'Langs het pad staan twaalf kunstinstallaties.',
          'Het bergpad is 2,5 kilometer lang.',
          'Jongeren en vrijwilligers hielpen mee met ontwerpen en maken.',
        ],
        question: 'Welk veilig weggegooid materiaal zou jij in een kunstwerk een tweede leven geven?',
        sourceLabel: 'UNESCO',
        sourceUrl: 'https://www.unesco.org/en/articles/perception-action-how-art-reshaping-climate-narratives?hub=66973',
        referenceUrl: '/img/vandaag-op-aarde/references/2026-08-29/china-eco-art-climate-lab.jpg',
        coloringSlug: 'china-mountain-eco-art-climate-project',
      },
      {
        slug: 'biodiversiteitsmaand-in-nieuw-zuid-wales',
        title: 'Buurtbewoners gaan op pad voor biodiversiteit',
        location: 'Nieuw-Zuid-Wales, Australië',
        reportedDate: '25 augustus 2026',
        theme: 'Natuur & samen doen',
        icon: '♧',
        intro: 'In de Central Tablelands staat een hele maand vol boomplantdagen, nachtwandelingen, kikkertochten en burgeronderzoek voor de natuur gepland.',
        body: 'Local Land Services kondigde een groot programma voor Biodiversity Month aan. Vrijwilligers kunnen in Farmers Creek en Glen Davis inheemse bomen planten. Bij Lake Pillans Wetlands neemt een natuurkenner bezoekers mee om in het donker naar kikkers te luisteren en te kijken. Andere groepen onderzoeken leefgebieden langs de Coxs River of gaan op zoek naar zweefbuideleekhoorns, possums en soms koala’s. Zo leren gezinnen niet alleen welke soorten in hun buurt leven, maar helpen ze ook om hun leefgebied te verbeteren.',
        facts: [
          'Biodiversity Month wordt in september gevierd.',
          'Er zijn activiteiten voor kinderen én volwassenen.',
          'Boomplantdagen maken nieuw leefgebied voor dieren.',
        ],
        question: 'Welk dier of welke plant zou jij in jouw buurt willen onderzoeken?',
        sourceLabel: 'NSW Local Land Services',
        sourceUrl: 'https://www.nsw.gov.au/departments-and-agencies/local-land-services/news/grab-your-boots-binoculars-and-torch-biodiversity-month-back',
        referenceUrl: '/img/vandaag-op-aarde/references/2026-08-29/nsw-biodiversity-month-grow-the-glen.jpg',
        coloringSlug: 'australia-biodiversity-month-community-planting',
      },
      {
        slug: 'roman-telescoop-naar-lanceerhangar',
        title: 'Roman-ruimtetelescoop rijdt naar de lanceerhangar',
        location: 'Florida, Verenigde Staten',
        reportedDate: '26 augustus 2026',
        theme: 'Ruimte & techniek',
        icon: '✦',
        intro: 'De Nancy Grace Roman Space Telescope reed veilig in zijn raketneus naar de hangar van lanceercomplex 39A, klaar voor de laatste voorbereidingen.',
        body: 'Op 25 augustus vervoerde een langzaam rijdend konvooi de Roman-telescoop over Kennedy Space Center. De telescoop zat volledig verborgen in de payload fairing: de hoge, puntige beschermkap boven op een raket. Op een speciale wagen met veel wielen bleef de lading rechtop, terwijl technici de temperatuur en andere waarden controleerden. In de hangar zou de fairing op een Falcon Heavy-raket worden geplaatst. Roman gaat later enorme stukken sterrenhemel fotograferen om onder meer donkere energie, donkere materie en planeten buiten ons zonnestelsel te bestuderen.',
        facts: [
          'De telescoop werd op 25 augustus 2026 naar de hangar gebracht.',
          'Tijdens het vervoer zat Roman volledig in de beschermende fairing.',
          'Roman krijgt een veel breder beeldveld dan Hubble.',
        ],
        question: 'Welke vraag over het heelal zou jij aan Roman willen meegeven?',
        sourceLabel: 'NASA',
        sourceUrl: 'https://www.nasa.gov/image-article/roman-space-telescope-travels-to-spacex-hangar/',
        referenceUrl: '/img/vandaag-op-aarde/references/2026-08-29/roman-telescope-transport-nasa.jpg',
        coloringSlug: 'roman-space-telescope-transport-kennedy',
      },
      {
        slug: 'erfgoedexperts-leren-objecten-bewaren',
        title: 'Erfgoedexperts leren voorwerpen veilig thuiskomen',
        location: 'Pretoria, Zuid-Afrika',
        reportedDate: '26 augustus 2026',
        theme: 'Cultuur & erfgoed',
        icon: '◇',
        intro: 'Zevenentwintig erfgoedprofessionals uit negen landen leren hoe historische voorwerpen eerlijk kunnen terugkeren en daarna veilig worden bewaard.',
        body: 'UNESCO, AUDA-NEPAD en de Universiteit van Pretoria organiseren twee cursussen over het teruggeven en conserveren van cultureel erfgoed. De deelnemers komen uit Botswana, Eswatini, Lesotho, Malawi, Mozambique, Namibië, Zuid-Afrika, Zambia en Zimbabwe. Ze bespreken wetgeving en ethiek, maar oefenen ook met voorzichtig hanteren, documenteren, opslaan en vertellen van mondelinge geschiedenis. Daarbij worden plaatselijke kennis en internationaal museumwerk gecombineerd. Zo kan een teruggekeerd voorwerp opnieuw betekenis krijgen in de gemeenschap waar het bij hoort.',
        facts: [
          'Aan de cursussen doen 27 professionals uit negen landen mee.',
          'De trainingen lopen van 11 tot en met 28 augustus 2026.',
          'Deelnemers leren over recht, opslag, documentatie en conservering.',
        ],
        question: 'Waarom is het belangrijk dat een voorwerp niet alleen terugkomt, maar ook goed wordt bewaard en uitgelegd?',
        sourceLabel: 'UNESCO',
        sourceUrl: 'https://www.unesco.org/en/articles/unesco-and-partners-build-expertise-return-and-restitution-cultural-property?hub=67817',
        referenceUrl: '/img/vandaag-op-aarde/references/2026-08-29/southern-africa-restitution-training.jpg',
        coloringSlug: 'southern-africa-heritage-conservation-training',
      },
    ],
  },
  {
    published: '2026-08-17',
    stories: [
      {
        slug: 'zonverduistering-boven-leon',
        title: 'Twee minuten donker bij een totale zonsverduistering',
        location: 'Spanje',
        reportedDate: '12 augustus 2026',
        theme: 'Ruimte & natuur',
        icon: '☀',
        intro: 'Op 12 augustus schoof de maan precies voor de zon. Bij León in Spanje werd het bijna twee minuten donker en verscheen de heldere zonnecorona rond de maan.',
        body: 'Een fotograaf van NASA Earth Observatory legde de totale zonsverduistering vast bij San Millán de los Caballeros, in de buurt van León. Eerst verdween steeds meer van de zon achter de maan. Tijdens de totaliteit bleef rondom de donkere maan een lichte, grillige ring zichtbaar: de buitenste atmosfeer van de zon, de corona. Aan de linkerkant was ook een heldere uitstulping te zien. Alleen tijdens de korte totaliteit kon zonder eclipsbril naar de volledig bedekte zon worden gekeken; vóór en erna bleef goede oogbescherming nodig.',
        facts: [
          'De totale zonsverduistering vond plaats op 12 augustus 2026.',
          'Bij León duurde de totaliteit ongeveer twee minuten.',
          'De corona is de hete buitenste atmosfeer van de zon.',
        ],
        question: 'Welke verandering in de natuur zou jij tijdens twee minuten duisternis willen waarnemen?',
        sourceLabel: 'NASA Earth Observatory',
        sourceUrl: 'https://science.nasa.gov/earth/earth-observatory/a-sunflowers-view-of-totality/',
        referenceUrl: 'https://science.nasa.gov/earth/earth-observatory/a-sunflowers-view-of-totality/',
        coloringSlug: 'total-solar-eclipse-leon-spain',
      },
      {
        slug: 'vier-leeuwenwelpen-een-jaar',
        title: 'Vier leeuwenwelpen zijn één jaar',
        location: 'Verenigde Staten',
        reportedDate: '13 augustus 2026',
        theme: 'Dieren',
        icon: '♌',
        intro: 'De vier leeuwenwelpen Alpine, Lily, Guion en Fraser werden op 13 augustus één jaar. Denver Zoo Conservation Alliance vierde hoeveel ze in hun eerste jaar zijn gegroeid.',
        body: 'De welpen werden vorig jaar geboren bij moeder Neliah en vader Tobias. Sindsdien leerden ze rennen, klimmen, spelen en steeds zelfstandiger eten. Rond hun eerste verjaardag hield het dierenteam de leeuwenfamilie tijdelijk samen binnen, omdat Olive van een kleine verwonding herstelde. Zo konden de dieren rustig bij elkaar blijven. De dierentuin deelde foto’s en verhalen om te laten zien hoe snel de vier jonge leeuwen zich hebben ontwikkeld.',
        facts: [
          'De vier welpen heten Alpine, Lily, Guion en Fraser.',
          'Ze werden op 13 augustus 2025 geboren.',
          'Jonge leeuwen leren veel door met elkaar en met volwassen leeuwen te spelen.',
        ],
        question: 'Welke vaardigheid zou jij een jonge leeuw als eerste willen zien oefenen?',
        sourceLabel: 'Denver Zoo Conservation Alliance',
        sourceUrl: 'https://denverzoo.org/events/lion-cub-birthday/',
        referenceUrl: 'https://denverzoo.org/zootales/baby-bulletin-introducing-our-lion-cub-quartet/',
        coloringSlug: 'four-lion-cubs-first-birthday-denver',
      },
      {
        slug: 'dinosaurussen-in-het-museum',
        title: 'Dinosaurusfossielen komen naar het museum',
        location: 'Verenigde Staten',
        reportedDate: '14 augustus 2026',
        theme: 'Wetenschap',
        icon: '◈',
        intro: 'In Chico opende op 14 augustus de tentoonstelling Dinosaurs: Fossils Exposed. Bezoekers kunnen echte fossielen en nauwkeurige skeletafgietsels van dichtbij bekijken.',
        body: 'Gateway Science Museum laat zien hoe paleontologen aan botten, tanden en afdrukken herkennen welke dieren vroeger leefden. In de tentoonstelling staan zes complete skeletafgietsels en dertien dinosauriërsschedels. Ook is er een enorm dijbeenfossiel van een Apatosaurus van bijna 1,9 meter lang. Met graafgereedschap en interactieve opdrachten kunnen kinderen zelf oefenen hoe een fossielenonderzoek werkt.',
        facts: [
          'De tentoonstelling loopt van 14 augustus 2026 tot 2 januari 2027.',
          'Er zijn zes complete skeletafgietsels en dertien schedels.',
          'Het Apatosaurus-dijbeen is ongeveer 1,85 meter lang.',
        ],
        question: 'Aan welk detail van een fossiel zou jij als eerste willen onderzoeken wat een dier at?',
        sourceLabel: 'Gateway Science Museum · Chico State',
        sourceUrl: 'https://www.csuchico.edu/gateway/exhibits/dinosaurs.shtml',
        referenceUrl: 'https://museumofdiscovery.org/exhibits-for-lease/',
        coloringSlug: 'dinosaur-fossils-exposed-museum-chico',
      },
      {
        slug: 'dak-vol-zonne-energie-hongkong',
        title: 'Bezoekers ontdekken een dak vol zonne-energie',
        location: 'Hongkong',
        reportedDate: '14 augustus 2026',
        theme: 'Duurzaamheid',
        icon: '☼',
        intro: 'Op 14 augustus konden bezoekers in Hongkong het Education Path verkennen. Op het dak zagen ze een groot veld met meer dan tweeduizend zonnepanelen.',
        body: 'Het Education Path van de Electrical and Mechanical Services Department heeft drie tentoonstellingsruimtes en een uitkijkgalerij op het dak. Daar leren bezoekers hoe gebouwen energie kunnen besparen en hoe zonlicht in elektriciteit verandert. Het zonnepanelenveld beslaat samen meer dan drieduizend vierkante meter. Tijdens de rondleiding konden kinderen goed zien hoe de panelen in rijen staan en waarom een vrije plek zonder veel schaduw belangrijk is.',
        facts: [
          'De rondleiding vond plaats op 14 augustus 2026.',
          'Op het dak liggen meer dan 2.000 zonnepanelen.',
          'De panelen beslaan samen meer dan 3.000 vierkante meter.',
        ],
        question: 'Op welke plek in jouw buurt zouden zonnepanelen veel zon kunnen vangen?',
        sourceLabel: 'Hong Kong EMSD',
        sourceUrl: 'https://wcms.emsd.gov.hk/en/about_us/public_education/guided_tour_on_education_path/index.html',
        referenceUrl: 'https://wcms.emsd.gov.hk/filemanager/en/content_1063/roof_viewing_gallery.jpg',
        coloringSlug: 'hong-kong-solar-energy-education-path',
      },
      {
        slug: 'wereldolifantendag',
        title: 'Wereldolifantendag zet olifanten in het zonnetje',
        location: 'Wereldwijd',
        reportedDate: '12 augustus 2026',
        theme: 'Dieren & natuur',
        icon: '◡',
        intro: 'Op 12 augustus was het Wereldolifantendag. Over de hele wereld deelden mensen kennis en ideeën om Aziatische en Afrikaanse olifanten te beschermen.',
        body: 'Wereldolifantendag begon in 2012 en wordt ieder jaar op 12 augustus gehouden. Organisaties, onderzoekers en dierenliefhebbers vragen dan aandacht voor veilige leefgebieden en een toekomst waarin mensen en olifanten goed naast elkaar kunnen leven. Olifanten zijn de grootste landdieren en leven in hechte familiegroepen. Door hun routes en leefgebieden te beschermen, krijgen kuddes ruimte om voedsel en water te vinden.',
        facts: [
          'Wereldolifantendag wordt sinds 2012 gehouden.',
          'Er bestaan Aziatische en Afrikaanse olifanten.',
          'Olifanten leven vaak in familiegroepen onder leiding van een ervaren vrouwtje.',
        ],
        question: 'Wat zou jij aan andere kinderen willen vertellen om olifanten te helpen?',
        sourceLabel: 'World Elephant Day',
        sourceUrl: 'https://worldelephantday.org/about/',
        referenceUrl: 'https://worldelephantday.org/assets/unnamed-1-3.jpg',
        coloringSlug: 'asian-elephant-world-elephant-day',
      },
    ],
  },
  {
    published: '2026-08-03',
    stories: [
      {
        slug: 'oude-fabriek-wordt-voetbalpark',
        title: 'Een oude fabriek wordt een voetbalpark',
        location: 'China',
        reportedDate: '3 augustus 2026',
        theme: 'Sport & hergebruik',
        icon: '⚽',
        intro: 'In de Chinese stad Zibo heeft een verlaten elektriciteitscentrale een verrassend nieuw leven gekregen. Tussen oude bakstenen gebouwen en een grote koeltoren liggen nu voetbalvelden waar kinderen, clubs en buurtteams samen kunnen spelen.',
        body: 'De bouwers maakten eerst twee kunstgrasvelden en voegden later twee velden met echt gras toe. De industriële gebouwen bleven staan, zodat je nog kunt zien waarvoor de plek vroeger werd gebruikt. Sinds de opening vonden er al meer dan 950 wedstrijden en activiteiten plaats. Zo laat het park zien dat je een oude plek niet altijd hoeft af te breken om er iets nieuws en vrolijks van te maken.',
        facts: [
          'Het terrein was vroeger een elektriciteitscentrale.',
          'Het voetbalpark heeft twee kunstgrasvelden en twee natuurgrasvelden.',
          'Er kwamen al meer dan 350 teams en ongeveer 42.000 bezoekers.',
        ],
        question: 'Welke lege plek in jouw buurt zou jij een nieuw leven geven?',
        sourceLabel: 'Xinhua',
        sourceUrl: 'https://english.news.cn/20260803/5aa7d79366c74e518ac5dde26b3aa2ef/c.html',
        referenceUrl: 'https://english.news.cn/20260803/5aa7d79366c74e518ac5dde26b3aa2ef/c.html',
        coloringSlug: 'old-factory-football-park-china',
      },
      {
        slug: 'nieuw-operatiecentrum-mozambique',
        title: 'Een nieuw centrum helpt straks meer patiënten',
        location: 'Mozambique',
        reportedDate: '3 augustus 2026',
        theme: 'Gezondheid',
        icon: '✚',
        intro: 'Bij het centrale ziekenhuis van Maputo is de bouw begonnen van een nieuw nationaal operatiecentrum. Artsen en verpleegkundigen krijgen er straks extra ruimte om patiënten uit heel Mozambique te behandelen.',
        body: 'Het gebouw wordt meer dan 20.000 vierkante meter groot en krijgt acht verdiepingen boven een kelder. Er komen veertien operatiekamers, negentien bedden voor intensieve zorg en 456 bedden voor patiënten die in het ziekenhuis blijven. De eerste steen is nu gelegd. Daarna volgen veel maanden van bouwen, installeren en testen voordat de deuren open kunnen.',
        facts: [
          'Het nieuwe centrum wordt groter dan 20.000 vierkante meter.',
          'Er komen veertien operatiekamers.',
          'Het plan telt 456 gewone bedden en negentien bedden voor intensieve zorg.',
        ],
        question: 'Welke ruimte zou in een fijn ziekenhuis niet mogen ontbreken?',
        sourceLabel: 'Xinhua',
        sourceUrl: 'https://english.news.cn/20260803/b8c18dd3b2214d21b531686feb161689/c.html',
        referenceUrl: 'https://english.news.cn/20260803/b8c18dd3b2214d21b531686feb161689/c.html',
        coloringSlug: 'new-surgical-center-maputo-mozambique',
      },
      {
        slug: 'beeld-onder-straatstenen',
        title: 'Een oud beeld lag eeuwen onder straatstenen',
        location: 'Turkije',
        reportedDate: '3 augustus 2026',
        theme: 'Geschiedenis',
        icon: '⌁',
        intro: 'In de oude stad Sardes hebben archeologen twee grote stukken van een marmeren beeld gevonden. Samen vormen ze een jonge man van ongeveer 2,2 meter hoog, gemaakt rond 470 tot 450 voor Christus.',
        body: 'Het beeld draagt bijzondere kleding met lange haren, een dikke mantel en fijne golvende lijnen. In zijn rechterhand houdt de jongeman een vrucht. Eeuwen later gebruikten bouwers het beeld opnieuw als steen in een Romeinse straat. Ze legden het met de voorkant naar beneden. Daardoor bleven het gezicht en veel details verrassend goed bewaard. Onderzoekers reinigen, fotograferen en onderzoeken het beeld nu voorzichtig.',
        facts: [
          'Het beeld is ongeveer 2.500 jaar oud en 2,2 meter hoog.',
          'Het werd in twee grote stukken gevonden.',
          'Doordat het met de voorkant naar beneden lag, bleven veel details beschermd.',
        ],
        question: 'Wat zou jij een archeoloog als eerste willen vragen?',
        sourceLabel: 'Xinhua',
        sourceUrl: 'https://english.news.cn/20260803/2115423a1ece4ab0a6a8675ae6b392a8/c.html',
        referenceUrl: 'https://www.manisakenthaberleri.com/sardeste-2-bin-500-yillik-heykel-bulundu',
        coloringSlug: 'ancient-lydian-statue-sardes-turkiye',
      },
      {
        slug: 'duikers-tellen-vissen',
        title: 'Duikers tellen vissen voor een gezond rif',
        location: 'Verenigde Staten',
        reportedDate: '3 augustus 2026',
        theme: 'Oceaan & meedoen',
        icon: '≋',
        intro: 'In Florida gingen duikers met REEF en de Adapt-Able Foundation op onderzoek uit. Eerst leerden ze vissen herkennen. Daarna maakten ze bij Key Largo een echte telling onder water.',
        body: 'Tijdens zo’n telling zwemmen duikers rustig door het gebied en noteren ze elke vissoort die ze zeker herkennen. Dat doen ze met een lei, speciaal watervast papier en een potlood dat met een koord vastzit. Na de duik sturen ze hun waarnemingen naar een grote databank. De gezamenlijke activiteit was zo ingericht dat mensen met verschillende lichamelijke of andere ondersteuningsbehoeften konden meedoen.',
        facts: [
          'De deelnemers oefenden eerst met het herkennen van vissoorten.',
          'Onder water gebruiken tellers een lei, watervast papier en een potlood.',
          'De waarnemingen helpen onderzoekers veranderingen in vispopulaties te volgen.',
        ],
        question: 'Welke vis zou jij onder water graag leren herkennen?',
        sourceLabel: 'REEF',
        sourceUrl: 'https://www.reef.org/news/enews/ocean-explorers-highlight-surveying-expedition-adapt-able-foundation',
        referenceUrl: 'https://www.reef.org/programs/volunteer-fish-survey-project',
        coloringSlug: 'adaptive-divers-fish-survey-florida',
      },
      {
        slug: 'asteroide-met-drie-delen',
        title: 'Een asteroïde met drie delen',
        location: 'Heelal',
        reportedDate: '3 augustus 2026',
        theme: 'Ruimte',
        icon: '✦',
        intro: 'Sterrenkundigen hebben nieuwe beelden gemaakt van Nysa, een asteroïde met een heel ongewone vorm. Het lijkt één rotslichaam met drie ongelijke delen die door twee smalle halzen met elkaar verbonden zijn.',
        body: 'Nysa is op het breedste punt ongeveer 75 kilometer groot. De vorm kan zijn ontstaan doordat drie kleinere brokken heel langzaam tegen elkaar kwamen en door zwaartekracht bij elkaar bleven. Er draait ook een klein maantje omheen, ongeveer één kilometer groot. De telescoopbeelden zijn nog wazig, maar door op verschillende momenten te kijken konden onderzoekers de draaiende vorm steeds beter begrijpen.',
        facts: [
          'Nysa is op het breedste punt ongeveer 75 kilometer groot.',
          'Het is de eerste bekende asteroïde met zo’n duidelijke vorm van drie verbonden delen.',
          'Het kleine maantje is ongeveer één kilometer groot.',
        ],
        question: 'Welke naam zou jij het kleine maantje geven?',
        sourceLabel: 'Space.com',
        sourceUrl: 'https://www.space.com/astronomy/asteroids/the-1st-three-headed-asteroid-space-photo-of-the-day-for-aug-3-2026',
        referenceUrl: 'https://www.space.com/astronomy/asteroids/1st-three-headed-asteroid-found-in-our-solar-system-and-it-has-a-little-moon',
        coloringSlug: 'three-lobed-asteroid-nysa',
      },
    ],
  },
  {
    published: '2026-07-27',
    stories: [
      {
        slug: 'sarnath-werelderfgoed',
        title: 'Een bijzondere plek krijgt een wereldster',
        location: 'India',
        reportedDate: '25 juli 2026',
        theme: 'Cultuur',
        icon: '⌒',
        intro: 'In het noorden van India ligt Sarnath, een plek met oude gebouwen, ruïnes en grote ronde torens van steen. Mensen komen hier al meer dan 2.500 jaar samen om te leren en stil te staan bij geschiedenis en cultuur.',
        body: 'Sarnath staat nu op de Werelderfgoedlijst van UNESCO. Een van de bekendste bouwwerken is de enorme Dhamek-stoepa. Archeologen vonden er ook oude beelden, pilaren en resten van kloosters. De nieuwe erkenning helpt om deze bijzondere plek goed te bewaren. Zo kunnen kinderen die er nu wonen én kinderen van later blijven ontdekken welke verhalen in de oude stenen verstopt zitten.',
        facts: [
          'Sarnath bestaat al meer dan 2.500 jaar.',
          'De Dhamek-stoepa is ongeveer 43 meter hoog.',
          'India heeft nu 45 UNESCO-werelderfgoedlocaties.',
        ],
        question: 'Welke plek bij jou in de buurt zou jij voor later willen bewaren?',
        sourceLabel: 'UNESCO',
        sourceUrl: 'https://www.unesco.org/en/articles/ancient-buddhist-site-sarnath-inscribed-unesco-world-heritage-list?hub=80094',
        referenceUrl: 'https://commons.wikimedia.org/wiki/File:Dhamek_Stupa_at_Sarnath_UP.jpg',
        coloringSlug: 'sarnath-dhamek-stupa-children-discovering-ancient-heritage',
      },
      {
        slug: 'veilige-rivier-voor-dolfijnen',
        title: 'Een veilige rivier voor zeldzame dolfijnen',
        location: 'Pakistan',
        reportedDate: '13 juli 2026',
        theme: 'Dieren',
        icon: '🐬',
        intro: 'In Pakistan hebben rivierdolfijnen een nieuw beschermd thuis gekregen. Een lang stuk van de Indus en de plek waar vijf rivieren samenkomen, heet voortaan het Punjnad Indus River Dolphin Sanctuary.',
        body: 'De Indusrivierdolfijn leeft niet in zee, maar in troebel rivierwater. Hij vindt zijn weg met kleine klikgeluidjes en luistert naar de echo die terugkomt. Het beschermde gebied is ongeveer 198 kilometer lang. Daar krijgen de dieren meer rust en ruimte om te zwemmen, eten te zoeken en jongen groot te brengen. Ook vissers, onderzoekers en natuurbeschermers gaan samenwerken om de rivier gezond te houden.',
        facts: [
          'De Indusrivierdolfijn leeft in zoet water.',
          'Hij gebruikt geluid en echo om de weg te vinden.',
          'Het nieuwe beschermde gebied is ongeveer 198 kilometer lang.',
        ],
        question: 'Hoe zou het zijn om vooral met geluid de weg te vinden?',
        sourceLabel: 'WWF',
        sourceUrl: 'https://www.worldwildlife.org/news/stories/indus-river-dolphins-benefit-from-new-protected-area-in-pakistan/',
        referenceUrl: 'https://www.worldwildlife.org/news/stories/indus-river-dolphins-benefit-from-new-protected-area-in-pakistan/',
        coloringSlug: 'indus-river-dolphin-sanctuary-pakistan',
      },
      {
        slug: 'bilbies-krijgen-hulp',
        title: 'Bilbies krijgen tien jaar extra hulp',
        location: 'Australië',
        reportedDate: '29 juni 2026',
        theme: 'Natuur',
        icon: '◡',
        intro: 'In de droge natuur van New South Wales werken onderzoekers, parkwachters en vrijwilligers samen om bijzondere Australische dieren terug te brengen. Hun natuurprojecten worden met tien jaar verlengd.',
        body: 'Een bilby is een klein nachtdier met lange oren en sterke graafpoten. Tijdens het graven maakt hij de harde grond los. Daardoor kan regenwater beter wegzakken en krijgen zaden ruimte om te groeien. In drie beschermde gebieden zijn inmiddels dertien diersoorten teruggebracht. Met tien jaar extra tijd kunnen de helpers blijven controleren hoe het met de dieren gaat en zorgen dat hun leefgebied veilig blijft.',
        facts: [
          'Een bilby is vooral ’s nachts wakker.',
          'Zijn tunnels kunnen ongeveer twee meter diep zijn.',
          'Bilbies helpen planten door de bodem los te graven.',
        ],
        question: 'Welk dier zou jij graag helpen met een veilig thuis?',
        sourceLabel: 'NSW Government',
        sourceUrl: 'https://www.nsw.gov.au/ministerial-releases/native-species-back-from-brink-nsw-commits-to-next-decade-of-wildlife-recovery',
        referenceUrl: 'https://www.nationalparks.nsw.gov.au/plants-and-animals/bilby',
        coloringSlug: 'greater-bilby-recovery-new-south-wales',
      },
      {
        slug: 'miljoen-zonnepanelen',
        title: 'Bijna een miljoen panelen vangen zonlicht',
        location: 'Verenigde Staten',
        reportedDate: '24 juli 2026',
        theme: 'Duurzaamheid',
        icon: '☼',
        intro: 'In een zonnige vallei in Utah zijn vanuit de ruimte rijen en rijen zonnepanelen te zien. Het Green River Energy Center heeft er 993.492 — bijna een miljoen.',
        body: 'De panelen zetten zonlicht om in elektriciteit. Bij de installatie staan ook 484 grote batterijen die energie kunnen bewaren voor later, bijvoorbeeld voor een moment waarop de zon niet schijnt. De Landsat 8-satelliet fotografeerde het gebied vanuit de ruimte. Zo kunnen onderzoekers precies bekijken hoe het landschap en de energievoorziening veranderen.',
        facts: [
          'Het project heeft 993.492 zonnepanelen.',
          'Er staan 484 grote batterijen om energie te bewaren.',
          'De ruimtefoto’s zijn gemaakt met de Landsat 8-satelliet.',
        ],
        question: 'Wat zou jij allemaal met één uur zonlicht willen laten werken?',
        sourceLabel: 'NASA Earth Observatory',
        sourceUrl: 'https://science.nasa.gov/earth/earth-observatory/a-million-panel-project/',
        referenceUrl: 'https://science.nasa.gov/earth/earth-observatory/a-million-panel-project/',
        coloringSlug: 'green-river-million-solar-panels-utah',
      },
      {
        slug: 'planeet-speelt-verstoppertje',
        title: 'Een reuzenplaneet speelt verstoppertje',
        location: 'Heelal',
        reportedDate: '15 juli 2026',
        theme: 'Ruimte',
        icon: '✦',
        intro: 'Bij de jonge ster Beta Pictoris kenden sterrenkundigen al twee grote planeten. Met de James Webb-ruimtetelescoop vonden ze nu nóg een wereld: Beta Pictoris d.',
        body: 'De planeet bleef lang verborgen in een heldere schijf van stof en steentjes rond de ster. In plaats van naar een lichtpuntje te zoeken, speurden onderzoekers naar een soort chemische vingerafdruk in de atmosfeer. Zo konden ze de planeet toch herkennen. Beta Pictoris d is waarschijnlijk minstens twee keer zo zwaar als Jupiter en draait heel ver van zijn ster. De slimme zoekmethode kan later helpen om meer planeten te vinden die zich in stoffige sterrenstelsels verstoppen.',
        facts: [
          'Beta Pictoris staat ongeveer 63 lichtjaar van de aarde.',
          'Het sterrenstelsel is ongeveer 23 miljoen jaar jong.',
          'De nieuwe planeet is waarschijnlijk minstens twee keer zo zwaar als Jupiter.',
        ],
        question: 'Welke naam zou jij geven aan een planeet die zich lang verstopt?',
        sourceLabel: 'NASA Webb',
        sourceUrl: 'https://science.nasa.gov/missions/webb/nasas-webb-discovers-hidden-planet-in-famous-star-system/',
        referenceUrl: 'https://www.esa.int/ESA_Multimedia/Images/2026/07/Beta_Pictoris_system_NIRSpec_IFU_image_and_spectrum',
        coloringSlug: 'beta-pictoris-d-hidden-exoplanet',
      },
    ],
  },
];
