/*
 * Verhalenarchief voor "Vandaag op Aarde".
 *
 * Nieuwe edities bovenaan toevoegen. Een kleurplaat is optioneel:
 * laat coloringSlug weg totdat de bijpassende tekening klaarstaat.
 */
const WORLD_STORY_EDITIONS = [
  {
    published: '2026-07-27',
    stories: [
      {
        slug: 'sarnath-werelderfgoed',
        title: 'Een bijzondere plek krijgt een wereldster',
        location: 'India',
        reportedDate: '25 juli 2026',
        theme: 'Cultuur',
        icon: '⌒',
        intro: 'In het noorden van India ligt Sarnath, een plek met oude gebouwen, ruïnes en grote ronde torens van steen. Mensen komen hier al meer dan 2.500 jaar samen om te leren en stil te staan bij geschiedenis en cultuur.',
        body: 'Sarnath staat nu op de Werelderfgoedlijst van UNESCO. Een van de bekendste bouwwerken is de enorme Dhamek-stoepa. Archeologen vonden er ook oude beelden, pilaren en resten van kloosters. De nieuwe erkenning helpt om deze bijzondere plek goed te bewaren. Zo kunnen kinderen die er nu wonen én kinderen van later blijven ontdekken welke verhalen in de oude stenen verstopt zitten.',
        facts: [
          'Sarnath bestaat al meer dan 2.500 jaar.',
          'De Dhamek-stoepa is ongeveer 43 meter hoog.',
          'India heeft nu 45 UNESCO-werelderfgoedlocaties.',
        ],
        question: 'Welke plek bij jou in de buurt zou jij voor later willen bewaren?',
        sourceLabel: 'UNESCO',
        sourceUrl: 'https://www.unesco.org/en/articles/ancient-buddhist-site-sarnath-inscribed-unesco-world-heritage-list?hub=80094',
        referenceUrl: 'https://commons.wikimedia.org/wiki/File:Dhamek_Stupa_at_Sarnath_UP.jpg',
      },
      {
        slug: 'veilige-rivier-voor-dolfijnen',
        title: 'Een veilige rivier voor zeldzame dolfijnen',
        location: 'Pakistan',
        reportedDate: '13 juli 2026',
        theme: 'Dieren',
        icon: '🐬',
        intro: 'In Pakistan hebben rivierdolfijnen een nieuw beschermd thuis gekregen. Een lang stuk van de Indus en de plek waar vijf rivieren samenkomen, heet voortaan het Punjnad Indus River Dolphin Sanctuary.',
        body: 'De Indusrivierdolfijn leeft niet in zee, maar in troebel rivierwater. Hij vindt zijn weg met kleine klikgeluidjes en luistert naar de echo die terugkomt. Het beschermde gebied is ongeveer 198 kilometer lang. Daar krijgen de dieren meer rust en ruimte om te zwemmen, eten te zoeken en jongen groot te brengen. Ook vissers, onderzoekers en natuurbeschermers gaan samenwerken om de rivier gezond te houden.',
        facts: [
          'De Indusrivierdolfijn leeft in zoet water.',
          'Hij gebruikt geluid en echo om de weg te vinden.',
          'Het nieuwe beschermde gebied is ongeveer 198 kilometer lang.',
        ],
        question: 'Hoe zou het zijn om vooral met geluid de weg te vinden?',
        sourceLabel: 'WWF',
        sourceUrl: 'https://www.worldwildlife.org/news/stories/indus-river-dolphins-benefit-from-new-protected-area-in-pakistan/',
        referenceUrl: 'https://www.worldwildlife.org/news/stories/indus-river-dolphins-benefit-from-new-protected-area-in-pakistan/',
        coloringSlug: 'dolphins-ocean',
      },
      {
        slug: 'bilbies-krijgen-hulp',
        title: 'Bilbies krijgen tien jaar extra hulp',
        location: 'Australië',
        reportedDate: '29 juni 2026',
        theme: 'Natuur',
        icon: '◡',
        intro: 'In de droge natuur van New South Wales werken onderzoekers, parkwachters en vrijwilligers samen om bijzondere Australische dieren terug te brengen. Hun natuurprojecten worden met tien jaar verlengd.',
        body: 'Een bilby is een klein nachtdier met lange oren en sterke graafpoten. Tijdens het graven maakt hij de harde grond los. Daardoor kan regenwater beter wegzakken en krijgen zaden ruimte om te groeien. In drie beschermde gebieden zijn inmiddels dertien diersoorten teruggebracht. Met tien jaar extra tijd kunnen de helpers blijven controleren hoe het met de dieren gaat en zorgen dat hun leefgebied veilig blijft.',
        facts: [
          'Een bilby is vooral ’s nachts wakker.',
          'Zijn tunnels kunnen ongeveer twee meter diep zijn.',
          'Bilbies helpen planten door de bodem los te graven.',
        ],
        question: 'Welk dier zou jij graag helpen met een veilig thuis?',
        sourceLabel: 'NSW Government',
        sourceUrl: 'https://www.nsw.gov.au/ministerial-releases/native-species-back-from-brink-nsw-commits-to-next-decade-of-wildlife-recovery',
        referenceUrl: 'https://www.nationalparks.nsw.gov.au/plants-and-animals/bilby',
      },
      {
        slug: 'miljoen-zonnepanelen',
        title: 'Bijna een miljoen panelen vangen zonlicht',
        location: 'Verenigde Staten',
        reportedDate: '24 juli 2026',
        theme: 'Duurzaamheid',
        icon: '☼',
        intro: 'In een zonnige vallei in Utah zijn vanuit de ruimte rijen en rijen zonnepanelen te zien. Het Green River Energy Center heeft er 993.492 — bijna een miljoen.',
        body: 'De panelen zetten zonlicht om in elektriciteit. Bij de installatie staan ook 484 grote batterijen die energie kunnen bewaren voor later, bijvoorbeeld voor een moment waarop de zon niet schijnt. De Landsat 8-satelliet fotografeerde het gebied vanuit de ruimte. Zo kunnen onderzoekers precies bekijken hoe het landschap en de energievoorziening veranderen.',
        facts: [
          'Het project heeft 993.492 zonnepanelen.',
          'Er staan 484 grote batterijen om energie te bewaren.',
          'De ruimtefoto’s zijn gemaakt met de Landsat 8-satelliet.',
        ],
        question: 'Wat zou jij allemaal met één uur zonlicht willen laten werken?',
        sourceLabel: 'NASA Earth Observatory',
        sourceUrl: 'https://science.nasa.gov/earth/earth-observatory/a-million-panel-project/',
        referenceUrl: 'https://science.nasa.gov/earth/earth-observatory/a-million-panel-project/',
      },
      {
        slug: 'planeet-speelt-verstoppertje',
        title: 'Een reuzenplaneet speelt verstoppertje',
        location: 'Heelal',
        reportedDate: '15 juli 2026',
        theme: 'Ruimte',
        icon: '✦',
        intro: 'Bij de jonge ster Beta Pictoris kenden sterrenkundigen al twee grote planeten. Met de James Webb-ruimtetelescoop vonden ze nu nóg een wereld: Beta Pictoris d.',
        body: 'De planeet bleef lang verborgen in een heldere schijf van stof en steentjes rond de ster. In plaats van naar een lichtpuntje te zoeken, speurden onderzoekers naar een soort chemische vingerafdruk in de atmosfeer. Zo konden ze de planeet toch herkennen. Beta Pictoris d is waarschijnlijk minstens twee keer zo zwaar als Jupiter en draait heel ver van zijn ster. De slimme zoekmethode kan later helpen om meer planeten te vinden die zich in stoffige sterrenstelsels verstoppen.',
        facts: [
          'Beta Pictoris staat ongeveer 63 lichtjaar van de aarde.',
          'Het sterrenstelsel is ongeveer 23 miljoen jaar jong.',
          'De nieuwe planeet is waarschijnlijk minstens twee keer zo zwaar als Jupiter.',
        ],
        question: 'Welke naam zou jij geven aan een planeet die zich lang verstopt?',
        sourceLabel: 'NASA Webb',
        sourceUrl: 'https://science.nasa.gov/missions/webb/nasas-webb-discovers-hidden-planet-in-famous-star-system/',
        referenceUrl: 'https://www.esa.int/ESA_Multimedia/Images/2026/07/Beta_Pictoris_system_NIRSpec_IFU_image_and_spectrum',
        coloringSlug: 'outer-space-planets',
      },
    ],
  },
];
